-- ═══════════════════════════════════════════════════════════════════
-- HLA · Modul Al-Quran · 001b: Metadata Surah (114 surah)
-- Run this entire file in: Supabase Dashboard → SQL Editor → New query
-- Run AFTER 001, and BEFORE 004 — 004 inserts modules with a surah_id
-- foreign key, which fails until this file has populated quran.surahs.
--
-- Nota reka bentuk: jadual ini hanya metadata surah (nama, bilangan
-- ayat, juzuk) — BUKAN teks ayat. Ia tidak tertakluk kepada Akta 326
-- atau lesen JAKIM (bandingkan dengan teks Uthmani penuh dalam
-- quran.ayahs, yang diimport melalui scripts/import-quran.mjs).
--
-- Ini membolehkan kurikulum (004) dan pelayar kurikulum di UI
-- berfungsi serta-merta tanpa menunggu fail sumber Tanzil, kerana
-- quran.modules.surah_id merujuk quran.surahs(id) sahaja.
--
-- Sumber: constants/surahIndex.ts (data sedia ada dalam repo ini).
-- ═══════════════════════════════════════════════════════════════════

insert into quran.surahs (id, name_arabic, name_rumi, name_malay, revelation_place, ayah_count, juz_start)
values
(1, 'الفاتحة', 'Al-Fatihah', 'Pembukaan', 'makkiyyah', 7, 1),
(2, 'البقرة', 'Al-Baqarah', 'Lembu Betina', 'madaniyyah', 286, 1),
(3, 'آل عمران', 'Ali ''Imran', 'Keluarga Imran', 'madaniyyah', 200, 3),
(4, 'النساء', 'An-Nisa''', 'Wanita', 'madaniyyah', 176, 4),
(5, 'المائدة', 'Al-Ma''idah', 'Hidangan', 'madaniyyah', 120, 6),
(6, 'الأنعام', 'Al-An''am', 'Binatang Ternakan', 'makkiyyah', 165, 7),
(7, 'الأعراف', 'Al-A''raf', 'Tempat Tertinggi', 'makkiyyah', 206, 8),
(8, 'الأنفال', 'Al-Anfal', 'Rampasan Perang', 'madaniyyah', 75, 9),
(9, 'التوبة', 'At-Taubah', 'Taubat', 'madaniyyah', 129, 10),
(10, 'يونس', 'Yunus', 'Nabi Yunus', 'makkiyyah', 109, 11),
(11, 'هود', 'Hud', 'Nabi Hud', 'makkiyyah', 123, 11),
(12, 'يوسف', 'Yusuf', 'Nabi Yusuf', 'makkiyyah', 111, 12),
(13, 'الرعد', 'Ar-Ra''d', 'Guruh', 'madaniyyah', 43, 13),
(14, 'إبراهيم', 'Ibrahim', 'Nabi Ibrahim', 'makkiyyah', 52, 13),
(15, 'الحجر', 'Al-Hijr', 'Batu Gunung', 'makkiyyah', 99, 14),
(16, 'النحل', 'An-Nahl', 'Lebah', 'makkiyyah', 128, 14),
(17, 'الإسراء', 'Al-Isra''', 'Perjalanan Malam', 'makkiyyah', 111, 15),
(18, 'الكهف', 'Al-Kahf', 'Gua', 'makkiyyah', 110, 15),
(19, 'مريم', 'Maryam', 'Maryam', 'makkiyyah', 98, 16),
(20, 'طه', 'Ta Ha', 'Ta Ha', 'makkiyyah', 135, 16),
(21, 'الأنبياء', 'Al-Anbiya''', 'Para Nabi', 'makkiyyah', 112, 17),
(22, 'الحج', 'Al-Hajj', 'Haji', 'madaniyyah', 78, 17),
(23, 'المؤمنون', 'Al-Mu''minun', 'Orang Mukmin', 'makkiyyah', 118, 18),
(24, 'النور', 'An-Nur', 'Cahaya', 'madaniyyah', 64, 18),
(25, 'الفرقان', 'Al-Furqan', 'Pembeza', 'makkiyyah', 77, 18),
(26, 'الشعراء', 'Asy-Syu''ara''', 'Penyair', 'makkiyyah', 227, 19),
(27, 'النمل', 'An-Naml', 'Semut', 'makkiyyah', 93, 19),
(28, 'القصص', 'Al-Qasas', 'Kisah-kisah', 'makkiyyah', 88, 20),
(29, 'العنكبوت', 'Al-''Ankabut', 'Labah-labah', 'makkiyyah', 69, 20),
(30, 'الروم', 'Ar-Rum', 'Bangsa Rom', 'makkiyyah', 60, 21),
(31, 'لقمان', 'Luqman', 'Luqman', 'makkiyyah', 34, 21),
(32, 'السجدة', 'As-Sajdah', 'Sujud', 'makkiyyah', 30, 21),
(33, 'الأحزاب', 'Al-Ahzab', 'Puak-puak Bersekutu', 'madaniyyah', 73, 21),
(34, 'سبأ', 'Saba''', 'Kaum Saba''', 'makkiyyah', 54, 22),
(35, 'فاطر', 'Fatir', 'Pencipta', 'makkiyyah', 45, 22),
(36, 'يس', 'Ya Sin', 'Ya Sin', 'makkiyyah', 83, 22),
(37, 'الصافات', 'As-Saffat', 'Berbaris-baris', 'makkiyyah', 182, 23),
(38, 'ص', 'Sad', 'Sad', 'makkiyyah', 88, 23),
(39, 'الزمر', 'Az-Zumar', 'Rombongan', 'makkiyyah', 75, 23),
(40, 'غافر', 'Ghafir', 'Yang Mengampuni', 'makkiyyah', 85, 24),
(41, 'فصلت', 'Fussilat', 'Yang Dijelaskan', 'makkiyyah', 54, 24),
(42, 'الشورى', 'Asy-Syura', 'Musyawarah', 'makkiyyah', 53, 25),
(43, 'الزخرف', 'Az-Zukhruf', 'Perhiasan Emas', 'makkiyyah', 89, 25),
(44, 'الدخان', 'Ad-Dukhan', 'Asap', 'makkiyyah', 59, 25),
(45, 'الجاثية', 'Al-Jasiyah', 'Berlutut', 'makkiyyah', 37, 25),
(46, 'الأحقاف', 'Al-Ahqaf', 'Bukit Pasir', 'makkiyyah', 35, 26),
(47, 'محمد', 'Muhammad', 'Nabi Muhammad', 'madaniyyah', 38, 26),
(48, 'الفتح', 'Al-Fath', 'Kemenangan', 'madaniyyah', 29, 26),
(49, 'الحجرات', 'Al-Hujurat', 'Bilik-bilik', 'madaniyyah', 18, 26),
(50, 'ق', 'Qaf', 'Qaf', 'makkiyyah', 45, 26),
(51, 'الذاريات', 'Az-Zariyat', 'Angin Yang Menerbangkan', 'makkiyyah', 60, 26),
(52, 'الطور', 'At-Tur', 'Bukit Tursina', 'makkiyyah', 49, 27),
(53, 'النجم', 'An-Najm', 'Bintang', 'makkiyyah', 62, 27),
(54, 'القمر', 'Al-Qamar', 'Bulan', 'makkiyyah', 55, 27),
(55, 'الرحمن', 'Ar-Rahman', 'Yang Maha Pemurah', 'madaniyyah', 78, 27),
(56, 'الواقعة', 'Al-Waqi''ah', 'Hari Kiamat', 'makkiyyah', 96, 27),
(57, 'الحديد', 'Al-Hadid', 'Besi', 'madaniyyah', 29, 27),
(58, 'المجادلة', 'Al-Mujadalah', 'Perempuan Yang Membantah', 'madaniyyah', 22, 28),
(59, 'الحشر', 'Al-Hasyr', 'Pengusiran', 'madaniyyah', 24, 28),
(60, 'الممتحنة', 'Al-Mumtahanah', 'Perempuan Yang Diuji', 'madaniyyah', 13, 28),
(61, 'الصف', 'As-Saff', 'Barisan', 'madaniyyah', 14, 28),
(62, 'الجمعة', 'Al-Jumu''ah', 'Hari Jumaat', 'madaniyyah', 11, 28),
(63, 'المنافقون', 'Al-Munafiqun', 'Orang Munafik', 'madaniyyah', 11, 28),
(64, 'التغابن', 'At-Taghabun', 'Hari Kekecewaan', 'madaniyyah', 18, 28),
(65, 'الطلاق', 'At-Talaq', 'Talak', 'madaniyyah', 12, 28),
(66, 'التحريم', 'At-Tahrim', 'Pengharaman', 'madaniyyah', 12, 28),
(67, 'الملك', 'Al-Mulk', 'Kerajaan', 'makkiyyah', 30, 29),
(68, 'القلم', 'Al-Qalam', 'Pena', 'makkiyyah', 52, 29),
(69, 'الحاقة', 'Al-Haqqah', 'Hari Kiamat', 'makkiyyah', 52, 29),
(70, 'المعارج', 'Al-Ma''arij', 'Tempat Naik', 'makkiyyah', 44, 29),
(71, 'نوح', 'Nuh', 'Nabi Nuh', 'makkiyyah', 28, 29),
(72, 'الجن', 'Al-Jinn', 'Jin', 'makkiyyah', 28, 29),
(73, 'المزمل', 'Al-Muzzammil', 'Orang Yang Berselimut', 'makkiyyah', 20, 29),
(74, 'المدثر', 'Al-Muddassir', 'Orang Yang Berselubung', 'makkiyyah', 56, 29),
(75, 'القيامة', 'Al-Qiyamah', 'Hari Kiamat', 'makkiyyah', 40, 29),
(76, 'الإنسان', 'Al-Insan', 'Manusia', 'madaniyyah', 31, 29),
(77, 'المرسلات', 'Al-Mursalat', 'Yang Diutus', 'makkiyyah', 50, 29),
(78, 'النبأ', 'An-Naba''', 'Berita Besar', 'makkiyyah', 40, 30),
(79, 'النازعات', 'An-Nazi''at', 'Malaikat Pencabut Nyawa', 'makkiyyah', 46, 30),
(80, 'عبس', '''Abasa', 'Bermuka Masam', 'makkiyyah', 42, 30),
(81, 'التكوير', 'At-Takwir', 'Menggulung', 'makkiyyah', 29, 30),
(82, 'الإنفطار', 'Al-Infitar', 'Terbelah', 'makkiyyah', 19, 30),
(83, 'المطففين', 'Al-Mutaffifin', 'Orang Yang Curang', 'makkiyyah', 36, 30),
(84, 'الانشقاق', 'Al-Insyiqaq', 'Terbelah', 'makkiyyah', 25, 30),
(85, 'البروج', 'Al-Buruj', 'Gugusan Bintang', 'makkiyyah', 22, 30),
(86, 'الطارق', 'At-Tariq', 'Bintang Yang Mengetuk', 'makkiyyah', 17, 30),
(87, 'الأعلى', 'Al-A''la', 'Yang Maha Tinggi', 'makkiyyah', 19, 30),
(88, 'الغاشية', 'Al-Ghasyiyah', 'Hari Pembalasan', 'makkiyyah', 26, 30),
(89, 'الفجر', 'Al-Fajr', 'Fajar', 'makkiyyah', 30, 30),
(90, 'البلد', 'Al-Balad', 'Negeri', 'makkiyyah', 20, 30),
(91, 'الشمس', 'Asy-Syams', 'Matahari', 'makkiyyah', 15, 30),
(92, 'الليل', 'Al-Lail', 'Malam', 'makkiyyah', 21, 30),
(93, 'الضحى', 'Ad-Duha', 'Waktu Dhuha', 'makkiyyah', 11, 30),
(94, 'الشرح', 'Asy-Syarh', 'Kelapangan', 'makkiyyah', 8, 30),
(95, 'التين', 'At-Tin', 'Buah Tin', 'makkiyyah', 8, 30),
(96, 'العلق', 'Al-''Alaq', 'Segumpal Darah', 'makkiyyah', 19, 30),
(97, 'القدر', 'Al-Qadr', 'Kemuliaan', 'makkiyyah', 5, 30),
(98, 'البينة', 'Al-Bayyinah', 'Bukti Yang Nyata', 'madaniyyah', 8, 30),
(99, 'الزلزلة', 'Az-Zalzalah', 'Gempa Bumi', 'madaniyyah', 8, 30),
(100, 'العاديات', 'Al-''Adiyat', 'Kuda Perang', 'makkiyyah', 11, 30),
(101, 'القارعة', 'Al-Qari''ah', 'Hari Kiamat', 'makkiyyah', 11, 30),
(102, 'التكاثر', 'At-Takasur', 'Bermegah-megah', 'makkiyyah', 8, 30),
(103, 'العصر', 'Al-''Asr', 'Masa', 'makkiyyah', 3, 30),
(104, 'الهمزة', 'Al-Humazah', 'Pengumpat', 'makkiyyah', 9, 30),
(105, 'الفيل', 'Al-Fil', 'Gajah', 'makkiyyah', 5, 30),
(106, 'قريش', 'Quraisy', 'Kaum Quraisy', 'makkiyyah', 4, 30),
(107, 'الماعون', 'Al-Ma''un', 'Bantuan', 'makkiyyah', 7, 30),
(108, 'الكوثر', 'Al-Kausar', 'Nikmat Yang Banyak', 'makkiyyah', 3, 30),
(109, 'الكافرون', 'Al-Kafirun', 'Orang Kafir', 'makkiyyah', 6, 30),
(110, 'النصر', 'An-Nasr', 'Pertolongan', 'madaniyyah', 3, 30),
(111, 'المسد', 'Al-Masad', 'Tali Dari Sabut', 'makkiyyah', 5, 30),
(112, 'الإخلاص', 'Al-Ikhlas', 'Keikhlasan', 'makkiyyah', 4, 30),
(113, 'الفلق', 'Al-Falaq', 'Waktu Subuh', 'makkiyyah', 5, 30),
(114, 'الناس', 'An-Nas', 'Manusia', 'makkiyyah', 6, 30)
on conflict (id) do update
  set name_arabic = excluded.name_arabic,
      name_rumi = excluded.name_rumi,
      name_malay = excluded.name_malay,
      revelation_place = excluded.revelation_place,
      ayah_count = excluded.ayah_count,
      juz_start = excluded.juz_start;
