-- ═══════════════════════════════════════════════════════════════════
-- Sunnah Seed Data: IDs 6–22
-- Run AFTER sunnah_schema.sql (which already loaded IDs 1–5)
-- Categories covered:
--   Bathroom Etiquette / آداب الحمام  (6–13)
--   Miswak / السواك                   (14–19)
--   Wudu' / الوضوء                    (20–22, continued in next file)
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO public.sunnah_items
  (id, title, arabic_title, arabic, transliteration, translation, source, narrator,
   category, time_of_day, topic, emoji, benefit, how_to, quiz, reflection, xp_reward)
VALUES

-- ── Bathroom Etiquette / آداب الحمام (6–13) ──────────────────────

(6,
 'Doa Masuk Tandas',
 'دُعَاءُ دُخُولِ الْخَلَاءِ',
 'بِسْمِ اللَّهِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
 'Bismillah. Allahumma inni a''udhu bika minal-khubuthi wal-khaba''ith',
 'Dengan nama Allah. Ya Allah, sesungguhnya aku berlindung kepada-Mu daripada syaitan jantan dan syaitan betina.',
 'Sahih al-Bukhari, Hadith 142', 'Diriwayatkan oleh Anas ibn Malik (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '🚻',
 'Tandas adalah tempat yang disukai syaitan. Doa ini adalah perisai rohani yang memohon perlindungan Allah sebelum memasuki tempat yang kotor. Ia mengajar kita untuk sentiasa bergantung kepada Allah dalam setiap keadaan, termasuk perkara yang kelihatan kecil.',
 E'1. Berdiri di luar pintu tandas\n2. Ucapkan Bismillah terlebih dahulu\n3. Baca doa perlindungan ini\n4. Baru masukkan kaki kiri ke dalam tandas\n5. Lakukan keperluan dengan tenang dan sopan',
 '{"question":"Mengapa kita perlu membaca doa sebelum masuk tandas?","options":["Supaya tandas menjadi bersih","Untuk berlindung dari gangguan syaitan","Sebagai tanda syukur","Untuk mendapat lebih banyak pahala"],"correctIndex":1,"explanation":"Tandas adalah tempat yang disukai syaitan. Rasulullah SAW mengajar kita membaca doa perlindungan dari khubuth (syaitan jantan) dan khaba''ith (syaitan betina). (Sahih al-Bukhari, Hadith 142)"}',
 'Kita memerlukan perlindungan Allah di mana sahaja. Dalam situasi lain apakah dalam hidupmu kamu rasa perlu memohon perlindungan Allah?',
 15),

(7,
 'Masuk Tandas Dengan Kaki Kiri',
 'تَقْدِيمُ الرِّجْلِ الْيُسْرَى لِدُخُولِ الْخَلَاءِ',
 'كَانَ يُقَدِّمُ رِجْلَهُ الْيُسْرَى حِينَ يَدْخُلُ الْخَلَاءَ',
 'Kana yuqaddimu rijlahul-yusra hina yadkhulul-khala''',
 'Baginda SAW mendahulukan kaki kirinya ketika memasuki tandas.',
 'Mustadrak al-Hakim, Hadith 604', 'Diriwayatkan oleh Anas ibn Malik (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '👣',
 'Dalam Islam, kaki kanan diutamakan untuk perkara mulia seperti masuk masjid dan memakai kasut. Kaki kiri pula diutamakan untuk perkara yang kurang mulia seperti masuk tandas. Ini mengajar kita tentang ketelitian adab Islam dalam setiap aspek kehidupan.',
 E'1. Tiba di hadapan pintu tandas\n2. Baca doa masuk tandas\n3. Angkat kaki kiri terlebih dahulu\n4. Langkah masuk dengan kaki kiri\n5. Kaki kanan mengikut selepasnya',
 '{"question":"Kaki manakah yang perlu didahulukan semasa masuk ke tandas?","options":["Kaki kanan","Kaki kiri","Mana-mana kaki","Tidak ada sunnah tentang ini"],"correctIndex":1,"explanation":"Rasulullah SAW mendahulukan kaki kiri ketika masuk ke tandas, berbeza dengan masuk masjid atau rumah yang mendahulukan kaki kanan. Ini adalah adab Islam yang diajar oleh baginda."}',
 'Islam mengajar adab dalam setiap perkara, walaupun perkara kecil. Apakah yang ini menunjukkan tentang pentingnya sunnah dalam kehidupan seharian?',
 10),

(8,
 'Tidak Menghadap atau Membelakangi Kiblat',
 'النَّهْيُ عَنِ اسْتِقْبَالِ الْقِبْلَةِ وَاسْتِدْبَارِهَا',
 'إِذَا أَتَيْتُمُ الْغَائِطَ فَلَا تَسْتَقْبِلُوا الْقِبْلَةَ وَلَا تَسْتَدْبِرُوهَا',
 'Idha ataytumul-gha''ita fala tastaqbilul-qiblata wala tastadbiruha',
 'Apabila kamu pergi buang air, janganlah kamu menghadap kiblat dan janganlah kamu membelakanginya.',
 'Sahih al-Bukhari, Hadith 394', 'Diriwayatkan oleh Abu Ayyub al-Ansari (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '🧭',
 'Kiblat adalah arah Ka''bah yang sangat dimuliakan dalam Islam. Larangan ini menunjukkan penghormatan kita kepada Ka''bah dan Allah SWT walaupun dalam keadaan buang air. Ini mengajar kita untuk menghormati perkara-perkara suci Islam dalam setiap situasi.',
 E'1. Sebelum duduk di dalam tandas\n2. Kenalpasti arah kiblat (ke arah barat laut di Malaysia)\n3. Pastikan badan tidak menghadap kiblat\n4. Pastikan badan juga tidak membelakangi kiblat\n5. Duduk dalam posisi yang dibenarkan',
 '{"question":"Apakah yang dilarang semasa buang air?","options":["Menghadap matahari","Menghadap atau membelakangi kiblat","Membuka alas kaki","Bergerak terlalu banyak"],"correctIndex":1,"explanation":"Rasulullah SAW melarang menghadap atau membelakangi kiblat semasa buang air sebagai tanda penghormatan kepada Ka''bah. (Sahih al-Bukhari, Hadith 394)"}',
 'Islam mengajar kita untuk menghormati arah kiblat dalam semua keadaan. Bagaimana kita boleh tunjukkan penghormatan kepada Allah dalam kehidupan harian?',
 15),

(9,
 'Diam dan Tidak Bercakap Dalam Tandas',
 'الصَّمْتُ فِي الْخَلَاءِ',
 'أَنَّ رَجُلًا مَرَّ عَلَى النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَهُوَ يَبُولُ فَسَلَّمَ عَلَيْهِ فَلَمْ يَرُدَّ عَلَيْهِ',
 'Anna rajulan marra ''alan-Nabiyyi sallallahu ''alayhi wa sallam wa huwa yabulu fasallama ''alayhi falam yarudda ''alayh',
 'Seorang lelaki lalu di sisi Nabi SAW ketika baginda sedang kencing, lalu lelaki itu memberi salam kepada baginda, tetapi baginda tidak membalas salamnya.',
 'Sahih Muslim, Hadith 370', 'Diriwayatkan oleh Jabir ibn Abdullah (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '🤫',
 'Tandas adalah tempat untuk melakukan hajat semata-mata. Bercakap atau berzikir secara lantang di dalam tandas adalah makruh kerana tidak menghormati nama Allah di tempat yang najis. Amalan diam ini juga menjaga privasi dan fokus.',
 E'1. Masuk ke tandas dengan diam\n2. Simpan atau tinggalkan telefon di luar\n3. Jangan berbual atau menjawab panggilan telefon\n4. Zikir hanya di dalam hati jika perlu\n5. Keluar terlebih dahulu sebelum bercakap atau menjawab salam',
 '{"question":"Apakah tindakan Rasulullah SAW ketika diberi salam semasa baginda kencing?","options":["Balas salam dengan kuat","Balas salam dengan isyarat tangan","Tidak membalas salam sehingga selesai","Meminta orang itu menunggu lama"],"correctIndex":2,"explanation":"Rasulullah SAW tidak membalas salam ketika sedang kencing kerana adab di tandas adalah diam. Baginda membalas salam setelah selesai dan berwudu''. (Sahih Muslim, Hadith 370)"}',
 'Terkadang kita perlu berhenti sejenak untuk menjaga adab. Dalam situasi apakah lagi kita perlu lebih berhati-hati tentang apa yang kita kata atau buat?',
 10),

(10,
 'Beristinja'' Dengan Tangan Kiri',
 'الِاسْتِنْجَاءُ بِالْيَدِ الْيُسْرَى',
 'لَا يُمْسِكَنَّ أَحَدُكُمْ ذَكَرَهُ بِيَمِينِهِ وَهُوَ يَبُولُ وَلَا يَتَمَسَّحْ مِنَ الْخَلَاءِ بِيَمِينِهِ',
 'La yumsikanna ahadukum zakarahu biyaninihi wa huwa yabulu wala yatamasahu minal-khala''i biyaninihi',
 'Janganlah seseorang kamu memegang kemaluannya dengan tangan kanan ketika kencing dan janganlah dia membersihkan dari tandas dengan tangan kanannya.',
 'Sahih al-Bukhari, Hadith 153', 'Diriwayatkan oleh Abu Qatadah (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '✋',
 'Tangan kanan adalah tangan yang dimuliakan — untuk makan, bersalam, dan menerima sesuatu. Tangan kiri pula dikhususkan untuk membersihkan najis. Pembahagian bijaksana ini menjaga kebersihan dan kehormatan tangan kanan kita.',
 E'1. Setelah selesai buang air\n2. Gunakan tangan kiri sahaja untuk istinja''\n3. Basuh kawasan yang bernajis dengan air menggunakan tangan kiri\n4. Pastikan kawasan benar-benar bersih dari najis\n5. Basuh tangan kiri dengan sabun selepasnya',
 '{"question":"Tangan manakah yang perlu digunakan untuk beristinja''?","options":["Tangan kanan","Tangan kiri","Mana-mana tangan boleh","Kedua-dua tangan serentak"],"correctIndex":1,"explanation":"Rasulullah SAW melarang menggunakan tangan kanan untuk istinja'' kerana tangan kanan adalah tangan yang mulia. Tangan kiri digunakan untuk perkara yang kotor. (Sahih al-Bukhari, Hadith 153)"}',
 'Islam membahagikan peranan tangan dengan bijaksana. Bagaimana kamu boleh lebih teliti dalam menjaga kebersihan mengikut sunnah?',
 15),

(11,
 'Istinja'' Dengan Bilangan Ganjil',
 'الْإِيتَارُ فِي الِاسْتِجْمَارِ',
 'إِذَا اسْتَجْمَرَ أَحَدُكُمْ فَلْيُوتِرْ',
 'Idha istajmara ahadukum falyutir',
 'Apabila seseorang kamu beristinja'' dengan batu, hendaklah dia menggunakan bilangan ganjil.',
 'Sahih al-Bukhari, Hadith 161', 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '🔢',
 'Bilangan ganjil (3, 5, 7) disukai dalam Islam kerana Allah Maha Ganjil dan menyukai bilangan ganjil. Prinsip ini juga digunakan dalam wudu'', zikir, dan banyak amalan Islam yang lain. Minimum tiga kali untuk memastikan kebersihan yang mencukupi.',
 E'1. Selesai buang air\n2. Gunakan tisu dengan tangan kiri\n3. Pastikan bilangan ganjil: 3, 5, atau 7 kali\n4. Minimum tiga kali untuk kebersihan yang cukup\n5. Selesaikan dengan air jika ada',
 '{"question":"Berapa bilangan yang perlu digunakan semasa beristinja''?","options":["Bilangan genap seperti 2 atau 4","Bilangan ganjil seperti 3 atau 5","Seberapa banyak yang diperlukan","Satu kali sudah mencukupi"],"correctIndex":1,"explanation":"Rasulullah SAW memerintahkan penggunaan bilangan ganjil semasa istinja''. Ini adalah prinsip witir (ganjil) yang disukai Allah SWT. (Sahih al-Bukhari, Hadith 161)"}',
 'Allah menyukai bilangan ganjil. Banyak amalan Islam menggunakan bilangan ganjil. Apakah hikmah di sebalik prinsip ini menurut pandangan kamu?',
 15),

(12,
 'Doa Keluar Tandas',
 'دُعَاءُ الْخُرُوجِ مِنَ الْخَلَاءِ',
 'غُفْرَانَكَ',
 'Ghufranaka',
 'Aku memohon keampunan-Mu.',
 'Sunan al-Tirmidhi, Hadith 7; Sunan Abu Dawud, Hadith 30',
 'Diriwayatkan oleh ''A''ishah (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '🚪',
 'Memohon keampunan Allah selepas keluar dari tandas mengajarkan kita untuk sentiasa sedar akan kelemahan diri. Kita memohon maaf kerana terpaksa menzahirkan aurat dan berada di tempat yang najis, serta memohon Allah menerima ibadah kita walaupun sering lalai.',
 E'1. Selesai keperluan di dalam tandas\n2. Bersedia untuk keluar\n3. Langkahkan kaki kanan keluar dahulu\n4. Terus baca: Ghufranaka\n5. Ucapkan dengan rendah hati dan penuh rasa memerlukan Allah',
 '{"question":"Apakah doa ringkas yang dibaca selepas keluar dari tandas?","options":["Alhamdulillah","Subhanallah","Ghufranaka","Bismillah"],"correctIndex":2,"explanation":"Rasulullah SAW membaca ''Ghufranaka'' (aku memohon keampunan-Mu) selepas keluar dari tandas. Ini diriwayatkan oleh ''A''ishah RA dan hadithnya sahih. (Sunan al-Tirmidhi, Hadith 7)"}',
 'Kita memohon keampunan Allah selepas melakukan keperluan sebagai manusia. Ini mengingatkan kita bahawa kita sentiasa memerlukan rahmat-Nya. Apakah lagi yang kamu ingin mohon ampun dari Allah hari ini?',
 15),

(13,
 'Keluar Tandas Dengan Kaki Kanan',
 'تَقْدِيمُ الرِّجْلِ الْيُمْنَى عِنْدَ الْخُرُوجِ مِنَ الْخَلَاءِ',
 'كَانَ يُقَدِّمُ رِجْلَهُ الْيُمْنَى حِينَ يَخْرُجُ مِنَ الْخَلَاءِ',
 'Kana yuqaddimu rijlahul-yumna hina yakhruju minal-khala''',
 'Baginda SAW mendahulukan kaki kanannya ketika keluar dari tandas.',
 'Al-Mustadrak al-Hakim; Ibn al-Sunni, ''Amal al-Yawm wal-Laylah',
 'Diriwayatkan oleh Anas ibn Malik (RA)',
 'Bathroom Etiquette', 'morning', 'Adab Tandas', '🚶',
 'Seperti masuk ke tempat mulia dengan kaki kanan, begitu juga keluar dari tempat kotor dengan kaki kanan. Ia melambangkan kita meninggalkan tempat yang tidak suci dan kembali kepada kehidupan yang bersih dan bermakna. Kaki kanan mewakili permulaan yang lebih baik.',
 E'1. Selesai keperluan di dalam tandas\n2. Bersedia untuk keluar\n3. Baca doa keluar tandas: Ghufranaka\n4. Langkahkan kaki KANAN keluar dahulu\n5. Kaki kiri mengikut selepas',
 '{"question":"Kaki manakah yang didahulukan semasa keluar dari tandas?","options":["Kaki kiri","Kaki kanan","Mana-mana kaki","Tidak ada sunnah tentang ini"],"correctIndex":1,"explanation":"Rasulullah SAW mendahulukan kaki kanan ketika keluar dari tandas — berlawanan dengan masuk yang menggunakan kaki kiri. Ini menunjukkan penghormatan kepada kaki kanan sebagai simbol kemuliaan."}',
 'Setiap langkah keluar dari tandas adalah permulaan baharu. Bagaimana kamu akan jadikan sisa hari ini lebih bermakna dengan amalan baik?',
 10),

-- ── Miswak / السواك (14–19) ──────────────────────────────────────

(14,
 'Bersugi (Miswak) Sebelum Setiap Solat',
 'السِّوَاكُ عِنْدَ كُلِّ صَلَاةٍ',
 'لَوْلَا أَنْ أَشُقَّ عَلَى أُمَّتِي لَأَمَرْتُهُمْ بِالسِّوَاكِ مَعَ كُلِّ صَلَاةٍ',
 'Lawla an ashuqqa ''ala ummati la-amartuhum bis-siwaki ma''a kulli salah',
 'Sekiranya tidak menyusahkan umatku, nescaya aku perintahkan mereka bersugi bersama setiap solat.',
 'Sahih al-Bukhari, Hadith 887', 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Miswak', 'morning', 'Kebersihan Mulut', '🦷',
 'Bersugi sebelum solat memastikan mulut kita bersih dan harum ketika berdiri di hadapan Allah SWT. Kajian sains membuktikan miswak mengandungi lebih 70 bahan aktif termasuk antibakteria, vitamin C, dan fluoride semula jadi — lebih berkesan daripada ubat gigi biasa!',
 E'1. Ambil miswak (batang kayu siwak)\n2. Basahkan hujung miswak dengan air\n3. Gigit sedikit untuk melembutkan hujungnya\n4. Mulakan dari sebelah kanan mulut\n5. Gosok gigi, gusi, dan lidah dengan lembut\n6. Bilas mulut dengan air bersih',
 '{"question":"Mengapa Rasulullah SAW tidak mewajibkan miswak sebelum setiap solat?","options":["Kerana miswak tidak penting","Kerana ia akan membebankan umat","Kerana miswak sukar didapati","Kerana cukup dengan ubat gigi"],"correctIndex":1,"explanation":"Rasulullah SAW sangat menggalakkan miswak tetapi tidak mewajibkannya kerana tidak mahu membebankan umat. Ini menunjukkan kasih sayang baginda kepada umatnya. (Sahih al-Bukhari, Hadith 887)"}',
 'Rasulullah SAW sangat mengambil berat tentang kebersihan. Bagaimana kamu boleh jadikan kebersihan sebagai satu bentuk ibadah kepada Allah?',
 20),

(15,
 'Bersugi Ketika Bangun Malam',
 'السِّوَاكُ عِنْدَ الْقِيَامِ مِنَ النَّوْمِ',
 'كَانَ إِذَا قَامَ مِنَ اللَّيْلِ يَشُوصُ فَاهُ بِالسِّوَاكِ',
 'Kana idha qama minal-layli yashusu fahu bis-siwak',
 'Baginda SAW apabila bangun pada waktu malam, baginda menggosok mulutnya dengan miswak.',
 'Sahih al-Bukhari, Hadith 245', 'Diriwayatkan oleh Huzaifah ibn al-Yaman (RA)',
 'Miswak', 'morning', 'Kebersihan Mulut', '🌙',
 'Semasa tidur, bakteria berkembang biak dalam mulut dan menyebabkan bau yang tidak sedap. Bersugi selepas bangun — sama ada untuk Tahajjud atau Subuh — membersihkan mulut dan menyegarkan nafas untuk memulakan ibadah dengan cara terbaik.',
 E'1. Apabila bangun dari tidur (malam atau pagi)\n2. Sebelum berwudu''\n3. Ambil miswak dan basahkan\n4. Gosok gigi dan gusi dengan teliti\n5. Baru berwudu'' dan solat',
 '{"question":"Apakah yang dilakukan Rasulullah SAW ketika bangun pada waktu malam?","options":["Terus membaca al-Quran","Menggosok mulut dengan miswak","Minum air suam","Membaca zikir tanpa bergerak"],"correctIndex":1,"explanation":"Hadith sahih menyebut Rasulullah SAW sentiasa menggosok mulut dengan miswak apabila bangun pada waktu malam sebelum solat. (Sahih al-Bukhari, Hadith 245)"}',
 'Kebersihan mulut adalah tanda menghormati Allah ketika berdoa dan membaca al-Quran. Apakah cara lain yang kamu boleh lakukan untuk menghormati waktu ibadah?',
 15),

(16,
 'Miswak — Pembersih Mulut dan Mendapat Redha Allah',
 'فَضْلُ السِّوَاكِ',
 'السِّوَاكُ مَطْهَرَةٌ لِلْفَمِ مَرْضَاةٌ لِلرَّبِّ',
 'As-siwaku mataharatun lil-fami mardaatun lir-Rabb',
 'Miswak itu pembersih bagi mulut dan mendapat keredaan Tuhan.',
 'Sahih al-Bukhari (mu''allaq); Sunan al-Nasa''i, Hadith 5',
 'Diriwayatkan oleh ''A''ishah (RA)',
 'Miswak', 'morning', 'Kebersihan Mulut', '✨',
 'Hadith ini menggabungkan dua faedah miswak: faedah zahir (membersihkan mulut) dan faedah batin (mendapat keredaan Allah). Amalan sunnah sentiasa mempunyai hikmah yang besar walaupun nampak kecil. Miswak adalah contoh terbaik ibadah yang merangkumi kesihatan dan kerohanian.',
 E'1. Amalkan miswak setiap hari\n2. Gunakan sebelum solat, sebelum wudu'', sebelum tidur\n3. Gunakan selepas makan\n4. Gantikan miswak setiap minggu atau apabila sudah usang\n5. Niati setiap penggunaan sebagai ibadah',
 '{"question":"Apakah dua faedah utama miswak yang disebut dalam hadith?","options":["Mencantikkan gigi dan menguatkan gusi","Membersihkan mulut dan mendapat keredaan Allah","Mencegah penyakit dan menambah tenaga","Menghilangkan lapar dan dahaga"],"correctIndex":1,"explanation":"Hadith menyatakan: mataharatun lil-fam (pembersih mulut) dan mardaatun lir-Rabb (mendapat keredaan Allah). Amalan kecil boleh mendatangkan redha Allah yang besar."}',
 'Amalan kecil seperti bersugi boleh mendapat keredaan Allah. Apakah amalan sunnah kecil lain yang kamu boleh amalkan setiap hari?',
 20),

(17,
 'Mendahulukan Sebelah Kanan Semasa Bersugi',
 'التَّيَمُّنُ فِي السِّوَاكِ',
 'كَانَ يُعْجِبُهُ التَّيَمُّنُ فِي تَنَعُّلِهِ وَتَرَجُّلِهِ وَطُهُورِهِ وَفِي شَأْنِهِ كُلِّهِ',
 'Kana yu''jibuhu tayammun fi tan''alihi wa tarajjulihi wa tuhurihi wa fi sha''nihi kullihi',
 'Baginda SAW suka mendahulukan yang kanan dalam memakai kasut, menyikat rambut, bersuci, dan dalam semua urusannya.',
 'Sahih al-Bukhari, Hadith 168', 'Diriwayatkan oleh ''A''ishah (RA)',
 'Miswak', 'morning', 'Kebersihan Mulut', '👉',
 'Prinsip tayammun (mendahulukan kanan) adalah sunnah Rasulullah SAW dalam semua perkara baik. Ketika bersugi, mulakan dari sebelah kanan mulut ke kiri. Prinsip ini mengajar kita tentang ketelitian dan ketertiban dalam setiap amalan Islam.',
 E'1. Ambil miswak yang sudah dibasahkan\n2. Masukkan ke dalam mulut dari sebelah kanan\n3. Gosok gigi sebelah kanan atas dahulu\n4. Kemudian kanan bawah\n5. Baru pindah ke sebelah kiri atas\n6. Akhir sekali kiri bawah dan lidah',
 '{"question":"Dari manakah Rasulullah SAW memulakan ketika bersugi?","options":["Dari sebelah kiri","Dari tengah mulut","Dari sebelah kanan","Dari bawah ke atas"],"correctIndex":2,"explanation":"Rasulullah SAW suka mendahulukan sebelah kanan dalam semua perkara baik termasuk bersugi. Ini adalah prinsip tayammun yang merupakan sunnah baginda dalam setiap urusan. (Sahih al-Bukhari, Hadith 168)"}',
 'Mendahulukan kanan adalah cara kita mengikut sunnah walaupun dalam perkara kecil. Apakah perkara lain hari ini yang kamu boleh amalkan prinsip mendahulukan kanan?',
 15),

(18,
 'Bersugi Sebelum Berwudu''',
 'السِّوَاكُ قَبْلَ الْوُضُوءِ',
 'السِّوَاكُ عِنْدَ كُلِّ وُضُوءٍ',
 'As-siwaku ''inda kulli wudu''',
 'Bersugi bersama setiap kali wudu''.',
 'Sunan Abu Dawud, Hadith 52; Musnad Ahmad',
 'Diriwayatkan oleh Anas ibn Malik (RA)',
 'Miswak', 'morning', 'Kebersihan Mulut', '💧',
 'Menggabungkan miswak dengan wudu'' adalah amalan yang sangat digalakkan. Wudu'' membersihkan anggota zahir kita, manakala miswak membersihkan mulut — tempat keluarnya al-Quran dan zikir. Kedua-dua amalan bersama-sama menyempurnakan kebersihan kita sebelum solat.',
 E'1. Sebelum mulakan wudu''\n2. Ambil miswak terlebih dahulu\n3. Gosok mulut dengan teliti\n4. Baru mulakan wudu'' dengan Bismillah\n5. Niati kedua-dua amalan sebagai ibadah kepada Allah',
 '{"question":"Bilakah masa yang digalakkan untuk bersugi selain sebelum solat?","options":["Hanya sekali sehari pada waktu pagi","Setiap kali sebelum berwudu''","Hanya pada hari Jumaat","Sekali seminggu sahaja"],"correctIndex":1,"explanation":"Hadith menggalakkan bersugi bersama setiap kali wudu''. Jika kita berwudu'' lima kali sehari untuk solat, kita juga bersugi lima kali. (Sunan Abu Dawud, Hadith 52)"}',
 'Menggabungkan beberapa amalan sunnah sekaligus mendatangkan lebih banyak pahala. Apakah amalan sunnah lain yang boleh kamu gabungkan dalam rutin harian?',
 15),

(19,
 'Bersugi Sebelum Membaca Al-Quran',
 'السِّوَاكُ قَبْلَ تِلَاوَةِ الْقُرْآنِ',
 'إِنَّ أَفْوَاهَكُمْ طُرُقُ الْقُرْآنِ فَطَيِّبُوهَا بِالسِّوَاكِ',
 'Inna afwahakum turuqul-Quran fatay-yibuha bis-siwak',
 'Sesungguhnya mulut kamu adalah jalan al-Quran, maka harumlah ia dengan miswak.',
 'Ibn Majah, Hadith 291; al-Bazzar',
 'Diriwayatkan oleh ''Ali ibn Abi Talib (RA)',
 'Miswak', 'morning', 'Kebersihan Mulut', '📖',
 'Mulut kita adalah jalan keluar bagi firman Allah — al-Quran. Adalah sangat wajar kita membersihkan dan mengharumkan laluan itu sebelum membaca kalam Allah. Ini adalah bentuk penghormatan tertinggi kepada al-Quran dan Penurunnya.',
 E'1. Sebelum duduk untuk membaca al-Quran\n2. Ambil wudu'' terlebih dahulu\n3. Bersugi dengan miswak untuk membersihkan mulut\n4. Duduk menghadap kiblat dengan adab\n5. Mulakan bacaan dengan Ta''awwuz dan Bismillah',
 '{"question":"Mengapa kita digalakkan bersugi sebelum membaca al-Quran?","options":["Supaya dapat membaca lebih laju","Kerana mulut adalah jalan al-Quran dan perlu bersih","Untuk mendapat lebih banyak pahala semata-mata","Kerana ia adalah wajib hukumnya"],"correctIndex":1,"explanation":"Hadith menjelaskan bahawa mulut kita adalah jalan al-Quran. Membersihkan mulut sebelum membaca al-Quran adalah bentuk penghormatan kepada firman Allah SWT. (Ibn Majah, Hadith 291)"}',
 'Al-Quran adalah firman Allah yang mulia. Apakah cara lain yang kamu boleh lakukan untuk menunjukkan penghormatan kepada al-Quran dalam kehidupan seharian?',
 20),

-- ── Wudu' / الوضوء (20–22) ───────────────────────────────────────

(20,
 'Niat Sebelum Berwudu''',
 'النِّيَّةُ عِنْدَ الْوُضُوءِ',
 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
 'Innamal-a''malu bin-niyyat wa innama likulli imri''in ma nawa',
 'Sesungguhnya setiap amalan itu bergantung kepada niatnya, dan setiap seseorang mendapat apa yang diniatkannya.',
 'Sahih al-Bukhari, Hadith 1; Sahih Muslim, Hadith 1907',
 'Diriwayatkan oleh ''Umar ibn al-Khattab (RA)',
 'Wudu''', 'morning', 'Bersuci', '🤲',
 'Niat adalah asas semua ibadah dalam Islam. Wudu'' yang diniatkan kerana Allah mendapat pahala walaupun sebelum solat bermula. Hadith tentang niat ini adalah hadith pertama dalam Sahih al-Bukhari — menunjukkan betapa agungnya peranan niat dalam setiap amalan.',
 E'1. Sebelum memulakan wudu''\n2. Berhenti sejenak dan hadirkan hati\n3. Niat dalam hati: "Aku niat berwudu'' untuk mengangkat hadas kecil kerana Allah"\n4. Niat tidak perlu dilafazkan — cukup dalam hati\n5. Terus mulakan wudu'' dengan Bismillah',
 '{"question":"Di manakah tempat niat dalam Islam?","options":["Di lidah — mesti dilafazkan","Di dalam hati","Di dalam fikiran sahaja","Boleh di mana-mana"],"correctIndex":1,"explanation":"Niat tempatnya di dalam hati. Ia tidak perlu dilafazkan dengan lidah dalam wudu'' dan solat. Hadith pertama Bukhari ini mengajar bahawa nilai amalan bergantung kepada niat di dalam hati."}',
 'Setiap amalan bernilai bergantung kepada niat. Apakah niat kamu dalam menuntut ilmu dan menjalani kehidupan seharian — adakah ia kerana Allah?',
 20),

(21,
 'Membaca Bismillah Sebelum Berwudu''',
 'التَّسْمِيَةُ قَبْلَ الْوُضُوءِ',
 'لَا وُضُوءَ لِمَنْ لَمْ يَذْكُرِ اسْمَ اللَّهِ عَلَيْهِ',
 'La wudu''a liman lam yadhkuri smallahi ''alayh',
 'Tidak sempurna wudu'' bagi orang yang tidak menyebut nama Allah ke atasnya.',
 'Sunan Abu Dawud, Hadith 101; Sunan Ibn Majah, Hadith 399',
 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Wudu''', 'morning', 'Bersuci', '✨',
 'Mengucapkan Bismillah sebelum wudu'' menjadikan wudu'' itu ibadah yang lengkap dan bermakna. Ia mengingatkan kita bahawa setiap perkara yang kita lakukan adalah dengan nama dan izin Allah. Para ulama berbeza pendapat tentang hukumnya — ramai berkata sunat muakkad (sangat dituntut).',
 E'1. Setelah niat di dalam hati\n2. Cucurkan air ke tangan\n3. Sebelum membasuh, ucapkan: Bismillahirrahmanirrahim\n4. Atau cukup dengan: Bismillah\n5. Terus mulakan wudu''',
 '{"question":"Apakah yang perlu diucapkan sebelum memulakan wudu''?","options":["Alhamdulillah","Bismillah","Subhanallah","La ilaha illallah"],"correctIndex":1,"explanation":"Rasulullah SAW mengajar kita untuk menyebut nama Allah (Bismillah) sebelum memulakan wudu''. Ini menjadikan wudu'' sebagai ibadah yang bermakna dan bukan sekadar cuci badan. (Sunan Abu Dawud, Hadith 101)"}',
 'Bismillah bermaksud memulakan dengan nama Allah. Bayangkan jika kamu mulakan SETIAP perkara dengan nama Allah — belajar, makan, kerja. Bagaimana ia akan mengubah hidupmu?',
 15),

(22,
 'Membasuh Tapak Tangan 3 Kali di Awal Wudu''',
 'غَسْلُ الْكَفَّيْنِ ثَلَاثًا فِي أَوَّلِ الْوُضُوءِ',
 'إِذَا اسْتَيْقَظَ أَحَدُكُمْ مِنْ نَوْمِهِ فَلَا يَغْمِسْ يَدَهُ فِي الْإِنَاءِ حَتَّى يَغْسِلَهَا ثَلَاثًا',
 'Idha istayqaza ahadukum min nawmihi fala yaghmis yadahu fil-ina''i hatta yaghsilaha thalatha',
 'Apabila seseorang kamu bangun tidur, janganlah dia mencelupkan tangannya ke dalam bekas air sehingga dia membasuhnya tiga kali.',
 'Sahih al-Bukhari, Hadith 162; Sahih Muslim, Hadith 278',
 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Wudu''', 'morning', 'Bersuci', '🙌',
 'Tangan kita menyentuh pelbagai benda semasa tidur tanpa kita sedari. Membasuh tangan tiga kali sebelum wudu'' adalah langkah kebersihan yang sangat bijaksana. Secara sains, ini mencegah pemindahan kuman dari tangan ke air wudu'' atau ke muka dan anggota lain.',
 E'1. Setelah baca Bismillah\n2. Buka paip atau ambil air\n3. Basuh tapak tangan kanan dan kiri bersama-sama\n4. Gosok dengan teliti termasuk celah jari\n5. Ulangi 3 kali sebelum menyentuh bekas air\n6. Baru mulakan wudu'' sebenar',
 '{"question":"Mengapa kita perlu membasuh tangan sebelum mencelupkannya ke dalam bekas air wudu''?","options":["Untuk menunjukkan hormat","Kerana tangan mungkin kotor semasa tidur","Supaya tangan menjadi lembut","Untuk mendinginkan tangan"],"correctIndex":1,"explanation":"Rasulullah SAW melarang mencelupkan tangan ke bekas air sebelum dibasuh tiga kali kerana kita tidak tahu apa yang tangan kita sentuh semasa tidur. Ini adalah langkah pencegahan kebersihan yang bijak. (Sahih al-Bukhari, Hadith 162)"}',
 'Tangan yang bersih bermula dari niat yang bersih. Adakah ada perkara dalam hidupmu yang perlu kamu ''bersihkan'' dari kebiasaan buruk?',
 15)

ON CONFLICT (id) DO NOTHING;
