-- ═══════════════════════════════════════════════════════════════════
-- Sunnah Seed Data: IDs 23–39
-- Run AFTER sunnah_seed_6_22.sql
-- Category: Wudu' / الوضوء (continued)
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO public.sunnah_items
  (id, title, arabic_title, arabic, transliteration, translation, source, narrator,
   category, time_of_day, topic, emoji, benefit, how_to, quiz, reflection, xp_reward)
VALUES

(23,
 'Berkumur-kumur (Madmadah) Dalam Wudu''',
 'الْمَضْمَضَةُ فِي الْوُضُوءِ',
 'ثُمَّ تَمَضْمَضَ وَاسْتَنْشَقَ وَاسْتَنْثَرَ ثَلَاثًا',
 'Thumma tamadmada wastansyaqa wastantsara thalatha',
 'Kemudian baginda berkumur, menghirup air ke hidung, dan meniupnya keluar, sebanyak tiga kali.',
 'Sahih al-Bukhari, Hadith 186; Sahih Muslim, Hadith 235',
 'Diriwayatkan oleh ''Uthman ibn ''Affan (RA)',
 'Wudu''', 'morning', 'Bersuci', '💦',
 'Berkumur (madmadah) membersihkan mulut, sisa makanan, dan kuman dari tekak dan lidah. Mulut yang bersih menyediakan kita untuk berzikir dan membaca al-Quran. Ini juga tindakan pencegahan penyakit mulut secara semula jadi.',
 E'1. Selepas basuh tangan\n2. Cedok air dengan tangan kanan\n3. Masukkan air ke dalam mulut\n4. Putar air dalam mulut dengan kuat\n5. Buangkan air ke luar\n6. Ulangi sebanyak 3 kali',
 '{"question":"Apakah nama sunnah berkumur-kumur dalam wudu''?","options":["Istinsyaq","Madmadah","Istintsar","Isbagh"],"correctIndex":1,"explanation":"Berkumur-kumur dalam wudu'' dipanggil madmadah. Ia dilakukan tiga kali dan merupakan sunnah penting dalam wudu''. Istinsyaq pula adalah menghirup air ke hidung. (Sahih al-Bukhari, Hadith 186)"}',
 'Wudu'' membersihkan badan secara menyeluruh. Apakah yang wudu'' ini mengajar kamu tentang pentingnya kebersihan menyeluruh dalam Islam?',
 15),

(24,
 'Istinsyaq dan Istintsar — Hidung Dalam Wudu''',
 'الِاسْتِنْشَاقُ وَالِاسْتِنْثَارُ فِي الْوُضُوءِ',
 'وَاسْتَنْشِقْ بِمَنْخِرَيْكَ مِنَ الْمَاءِ ثُمَّ انْتَثِرْ',
 'Wastansyiq bimankhirayika minal-ma''i thumma antathir',
 'Dan hiruplah air dengan kedua lubang hidungmu, kemudian hembuskan.',
 'Sahih al-Bukhari, Hadith 162', 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Wudu''', 'morning', 'Bersuci', '👃',
 'Istinsyaq (menghirup air ke hidung) membersihkan bahagian dalam hidung dari habuk dan kuman. Kajian sains menunjukkan bahawa membasuh hidung dengan air dapat mencegah jangkitan saluran pernafasan. Rasulullah SAW telah mengajar amalan kesihatan ini 1,400 tahun lalu!',
 E'1. Selepas berkumur (madmadah)\n2. Gunakan tangan kanan untuk cedok air\n3. Hirup air ke dalam hidung (istinsyaq)\n4. Tahan sebentar\n5. Gunakan tangan kiri untuk hembuskan keluar (istintsar)\n6. Ulangi 3 kali',
 '{"question":"Apakah perbezaan antara istinsyaq dan istintsar?","options":["Kedua-duanya sama sahaja","Istinsyaq menghirup air ke hidung, istintsar meniupnya keluar","Istinsyaq untuk mulut, istintsar untuk hidung","Istinsyaq dilakukan 3 kali, istintsar sekali"],"correctIndex":1,"explanation":"Istinsyaq adalah menghirup air ke dalam hidung (tangan kanan), manakala istintsar adalah meniup air keluar dari hidung (tangan kiri). Kedua-dua dilakukan bersama dalam wudu''. (Sahih al-Bukhari, Hadith 162)"}',
 'Rasulullah SAW mengajar amalan kesihatan yang terbukti sains 1,400 tahun kemudian. Apakah yang ini mengajar kamu tentang hikmah di sebalik sunnah-sunnah baginda?',
 15),

(25,
 'Membasuh Muka 3 Kali Dalam Wudu''',
 'غَسْلُ الْوَجْهِ فِي الْوُضُوءِ',
 'يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا قُمْتُمْ إِلَى الصَّلَاةِ فَاغْسِلُوا وُجُوهَكُمْ',
 'Ya ayyuhal-ladhina amanu idha qumtum ilas-salati faghsilu wujuhakum',
 'Wahai orang-orang yang beriman, apabila kamu berdiri untuk solat, maka basuhlah muka kamu.',
 'Al-Quran, Surah al-Ma''idah 5:6', 'Firman Allah SWT',
 'Wudu''', 'morning', 'Bersuci', '😊',
 'Membasuh muka adalah rukun wudu'' yang wajib seperti diperintahkan Allah dalam al-Quran. Had muka yang wajib: dari dahi hingga dagu, dari telinga ke telinga. Membasuh tiga kali adalah sunnah manakala sekali adalah fardu minimum.',
 E'1. Cedok air dengan kedua tangan\n2. Ratakan air dari dahi hingga dagu\n3. Dari telinga kanan ke telinga kiri\n4. Pastikan seluruh muka kena air\n5. Sela janggut dengan air jika lebat\n6. Ulangi 3 kali',
 '{"question":"Apakah had muka yang wajib dibasuh dalam wudu''?","options":["Dari kening ke hidung sahaja","Dari dahi ke dagu, dari telinga ke telinga","Dari hidung ke dagu sahaja","Dari atas kepala ke leher"],"correctIndex":1,"explanation":"Had muka yang wajib dibasuh adalah dari dahi (garis rambut) ke dagu, dan dari telinga kanan ke telinga kiri. Berdasarkan al-Quran 5:6 dan penjelasan para ulama fiqh."}',
 'Setiap kali basuh muka dalam wudu'', bayangkan dosa berguguran bersama titisan air. Apakah perasaan kamu bila membayangkan ini?',
 20),

(26,
 'Membasuh Tangan Kanan Hingga Siku',
 'غَسْلُ الْيَدِ الْيُمْنَى إِلَى الْمِرْفَقِ',
 'وَأَيْدِيَكُمْ إِلَى الْمَرَافِقِ',
 'Wa aydiyakum ilal-marafiq',
 'Dan tangan kamu hingga siku.',
 'Al-Quran, Surah al-Ma''idah 5:6', 'Firman Allah SWT',
 'Wudu''', 'morning', 'Bersuci', '💪',
 'Allah memerintahkan membasuh tangan hingga siku — memastikan bahagian yang paling kerap menyentuh sesuatu dibersihkan dengan sempurna. Tangan kanan dibasuh dahulu mengikut prinsip mendahulukan kanan dalam semua perkara mulia.',
 E'1. Selepas basuh muka\n2. Mulakan dengan tangan kanan\n3. Basuh dari hujung jari hingga melepasi siku\n4. Pastikan siku kena air (ini wajib)\n5. Gosok dengan teliti termasuk celah jari\n6. Ulangi 3 kali sebelum beralih ke tangan kiri',
 '{"question":"Sejauh manakah tangan perlu dibasuh dalam wudu''?","options":["Hingga pergelangan tangan","Hingga siku","Hingga bahu","Hingga hujung jari sahaja"],"correctIndex":1,"explanation":"Allah SWT berfirman: ''wa aydiyakum ilal-marafiq'' — tangan hingga siku. Siku mesti dibasuh kerana ia termasuk dalam had yang diperintahkan. (Surah al-Ma''idah 5:6)"}',
 'Apabila membasuh tanganmu dalam wudu'', renunglah — apakah yang tangan ini akan lakukan hari ini? Kebaikan atau sebaliknya?',
 15),

(27,
 'Membasuh Tangan Kiri Hingga Siku',
 'غَسْلُ الْيَدِ الْيُسْرَى إِلَى الْمِرْفَقِ',
 'ثُمَّ أَفَاضَ عَلَى يَدِهِ الْيُسْرَى فَغَسَلَهَا ثَلَاثَ مَرَّاتٍ',
 'Thumma afada ''ala yadihil-yusra faghasalaha thalatha marratin',
 'Kemudian baginda menuangkan air ke tangan kirinya dan membasuhnya tiga kali.',
 'Sahih al-Bukhari, Hadith 186; Sahih Muslim, Hadith 226',
 'Diriwayatkan oleh ''Uthman ibn ''Affan (RA)',
 'Wudu''', 'morning', 'Bersuci', '🤚',
 'Selepas tangan kanan, tangan kiri pula dibasuh dengan cara yang sama. Tertib adalah penting — kanan dahulu, baru kiri. Setiap anggota dibasuh dengan sempurna menunjukkan perhatian penuh kepada ibadah kita kepada Allah.',
 E'1. Selepas selesai basuh tangan kanan 3 kali\n2. Beralih ke tangan kiri\n3. Basuh dari hujung jari hingga melepasi siku\n4. Pastikan tiada bahagian yang kering\n5. Gosok celah jari dengan teliti\n6. Ulangi 3 kali',
 '{"question":"Apakah urutan yang betul membasuh tangan dalam wudu''?","options":["Kiri dahulu kemudian kanan","Kanan dahulu kemudian kiri","Boleh mana-mana dahulu","Kedua-dua serentak"],"correctIndex":1,"explanation":"Sunnah Rasulullah SAW adalah mendahulukan tangan kanan sebelum tangan kiri dalam wudu''. Ini adalah prinsip tayammun yang diamalkan baginda dalam setiap urusan. (Sahih al-Bukhari, Hadith 186)"}',
 'Wudu'' mengajar kita tentang ketertiban dan perhatian kepada setiap bahagian. Adakah ada bahagian dalam hidupmu yang kamu abaikan dan perlu lebih diberi perhatian?',
 15),

(28,
 'Menyapu Kepala Dalam Wudu''',
 'مَسْحُ الرَّأْسِ فِي الْوُضُوءِ',
 'وَامْسَحُوا بِرُؤُوسِكُمْ',
 'Wamsahu biru''usikum',
 'Dan usaplah kepala kamu.',
 'Al-Quran, Surah al-Ma''idah 5:6', 'Firman Allah SWT',
 'Wudu''', 'morning', 'Bersuci', '👆',
 'Berbeza dengan anggota lain yang dibasuh dengan air, kepala hanya disapu (diusap) dengan tangan yang basah. Yang lebih afdal adalah mengusap seluruh kepala — dari dahi ke belakang kepala, kemudian balik ke depan — sebagaimana yang dilakukan Rasulullah SAW.',
 E'1. Selepas basuh kedua-dua tangan\n2. Basahkan kedua-dua tangan\n3. Letakkan kedua tangan di bahagian depan kepala (dahi)\n4. Jalankan dari depan ke belakang kepala\n5. Kemudian tarik balik dari belakang ke depan\n6. Ini dikira satu kali sapu — tidak diulang',
 '{"question":"Bagaimanakah cara yang betul mengusap kepala dalam wudu''?","options":["Basuh dengan air seperti muka","Sapu dengan tangan yang basah dari depan ke belakang","Sapu hanya bahagian tepi kepala","Cukup sapu sedikit rambut di hadapan"],"correctIndex":1,"explanation":"Mengusap kepala dalam wudu'' menggunakan tangan yang basah — bukan dituangkan air. Rasulullah SAW mengusap dari dahi ke belakang kepala kemudian balik ke depan. (Sahih al-Bukhari, Hadith 185)"}',
 'Kepala adalah tempat akal dan fikiran. Ketika mengusap kepala dalam wudu'', doakan agar Allah beri hidayah dan ilmu yang bermanfaat. Apakah yang ingin kamu minta dari Allah hari ini?',
 15),

(29,
 'Menyapu Kedua-dua Telinga Dalam Wudu''',
 'مَسْحُ الْأُذُنَيْنِ فِي الْوُضُوءِ',
 'الْأُذُنَانِ مِنَ الرَّأْسِ',
 'Al-udhunani minar-ra''s',
 'Kedua-dua telinga adalah sebahagian dari kepala.',
 'Sunan Abu Dawud, Hadith 134; Sunan Ibn Majah, Hadith 444',
 'Diriwayatkan oleh Ibn ''Abbas (RA)',
 'Wudu''', 'morning', 'Bersuci', '👂',
 'Telinga adalah sebahagian dari kepala, maka ia juga disapu dalam wudu''. Caranya: jari telunjuk untuk bahagian dalam (lubang telinga) dan ibu jari untuk bahagian luar (belakang telinga). Ini membersihkan kawasan sekeliling telinga dari habuk dan kotoran.',
 E'1. Selepas mengusap kepala\n2. Gunakan air yang tinggal pada tangan (tidak perlu air baru)\n3. Masukkan kedua jari telunjuk ke dalam lubang telinga\n4. Ibu jari mengusap bahagian belakang telinga\n5. Lakukan serentak untuk kedua-dua telinga\n6. Dilakukan sekali sahaja',
 '{"question":"Bagaimanakah cara menyapu telinga dalam wudu''?","options":["Tuangkan air ke dalam telinga","Jari telunjuk untuk bahagian dalam, ibu jari untuk bahagian luar","Cukup lap dengan tuala","Sapu bahagian luar telinga sahaja"],"correctIndex":1,"explanation":"Cara menyapu telinga: jari telunjuk ke dalam lubang telinga, ibu jari mengusap bahagian belakang. Dilakukan sekali serentak untuk kedua-dua telinga. (Sunan Abu Dawud, Hadith 134)"}',
 'Telinga yang telah diusap dalam wudu'' — gunakan untuk mendengar perkara yang baik. Apakah perkara baik yang ingin kamu dengar dan pelajari hari ini?',
 10),

(30,
 'Membasuh Kaki Kanan Hingga Buku Lali',
 'غَسْلُ الرِّجْلِ الْيُمْنَى إِلَى الْكَعْبَيْنِ',
 'وَأَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ',
 'Wa arjulakum ilal-ka''bayn',
 'Dan kaki kamu hingga buku lali.',
 'Al-Quran, Surah al-Ma''idah 5:6', 'Firman Allah SWT',
 'Wudu''', 'morning', 'Bersuci', '🦶',
 'Kaki adalah anggota terakhir yang dibasuh dalam wudu'' dan sering diabaikan. Rasulullah SAW pernah melihat sahabat yang meninggalkan sebahagian kecil tumit tidak kena air dan memberi amaran keras. Kaki kanan dibasuh dahulu mengikut sunnah.',
 E'1. Selepas mengusap telinga\n2. Mulakan dengan kaki kanan\n3. Basuh dari hujung jari hingga melepasi buku lali\n4. Sela celah jari kaki dengan jari kelingking tangan kiri\n5. Pastikan kawasan tumit kena air\n6. Ulangi 3 kali sebelum beralih ke kaki kiri',
 '{"question":"Sejauh manakah kaki perlu dibasuh dalam wudu''?","options":["Hingga lutut","Hingga buku lali (mata kaki)","Hujung jari kaki sahaja","Hingga betis"],"correctIndex":1,"explanation":"Allah SWT berfirman: ''wa arjulakum ilal-ka''bayn'' — kaki hingga buku lali. Buku lali mesti dibasuh kerana termasuk dalam had yang diperintahkan. (Surah al-Ma''idah 5:6)"}',
 'Rasulullah SAW mengingatkan tentang bahagian kecil kaki yang tidak dibasuh. Ini mengajar kita untuk teliti dalam ibadah. Adakah ada ibadah lain yang kamu perlu lebih teliti?',
 15),

(31,
 'Membasuh Kaki Kiri Hingga Buku Lali',
 'غَسْلُ الرِّجْلِ الْيُسْرَى إِلَى الْكَعْبَيْنِ',
 'وَكَانَ يَغْسِلُ قَدَمَيْهِ ثَلَاثًا ثَلَاثًا',
 'Wa kana yaghsilu qadamayhi thalathan thalatha',
 'Dan baginda SAW membasuh kedua-dua kakinya tiga kali tiga kali.',
 'Sahih al-Bukhari, Hadith 186', 'Diriwayatkan oleh ''Uthman ibn ''Affan (RA)',
 'Wudu''', 'morning', 'Bersuci', '🦵',
 'Kaki kiri dibasuh selepas kaki kanan mengikut urutan sunnah. Rasulullah SAW membasuh setiap kaki tiga kali dan sangat teliti memastikan air mengenai setiap bahagian termasuk tumit dan celah jari kaki. Wudu'' yang lengkap memerlukan perhatian kepada setiap detail.',
 E'1. Selepas selesai kaki kanan 3 kali\n2. Beralih ke kaki kiri\n3. Basuh dari hujung jari hingga melepasi buku lali\n4. Sela celah jari kaki dengan jari kelingking tangan kiri\n5. Jangan lupa kawasan tumit\n6. Ulangi 3 kali',
 '{"question":"Apakah urutan yang betul membasuh kaki dalam wudu''?","options":["Kiri dahulu kemudian kanan","Kanan dahulu kemudian kiri","Kedua-dua serentak","Tidak ada urutan tertentu"],"correctIndex":1,"explanation":"Mengikut sunnah Rasulullah SAW, kaki kanan dibasuh dahulu diikuti kaki kiri. Hadith ''Uthman RA menghuraikan cara wudu'' Rasulullah SAW secara terperinci. (Sahih al-Bukhari, Hadith 186)"}',
 'Wudu'' yang sempurna memerlukan perhatian kepada setiap bahagian kecil. Adakah ada bahagian dalam kehidupanmu yang kamu abaikan dan perlu lebih perhatian?',
 15),

(32,
 'Tertib — Mengikut Urutan Dalam Wudu''',
 'التَّرْتِيبُ فِي الْوُضُوءِ',
 'يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا قُمْتُمْ إِلَى الصَّلَاةِ فَاغْسِلُوا وُجُوهَكُمْ وَأَيْدِيَكُمْ إِلَى الْمَرَافِقِ وَامْسَحُوا بِرُؤُوسِكُمْ وَأَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ',
 'Ya ayyuhal-ladhina amanu idha qumtum ilas-salati faghsilu wujuhakum wa aydiyakum ilal-marafiq wamsahu biru''usikum wa arjulakum ilal-ka''bayn',
 'Wahai orang yang beriman! Apabila kamu berdiri untuk solat, basuhlah muka kamu, tangan hingga siku, sapu kepala, dan kaki hingga buku lali.',
 'Al-Quran, Surah al-Ma''idah 5:6', 'Firman Allah SWT',
 'Wudu''', 'morning', 'Bersuci', '📋',
 'Tertib bermaksud mengikut urutan yang Allah tetapkan dalam al-Quran: muka → tangan kanan → tangan kiri → sapu kepala → kaki kanan → kaki kiri. Jika urutan diubah (contoh: basuh tangan sebelum muka), wudu'' tidak sah mengikut mazhab Syafii.',
 E'Urutan wudu'' yang betul:\n1. Niat\n2. Bismillah\n3. Basuh tangan 3x\n4. Berkumur 3x\n5. Istinsyaq & istintsar 3x\n6. Basuh muka 3x\n7. Basuh tangan kanan 3x\n8. Basuh tangan kiri 3x\n9. Sapu kepala\n10. Sapu telinga\n11. Basuh kaki kanan 3x\n12. Basuh kaki kiri 3x\n13. Doa selepas wudu''',
 '{"question":"Apakah urutan yang betul dalam wudu'' mengikut al-Quran?","options":["Tangan, muka, kepala, kaki","Muka, tangan, kepala, kaki","Muka, kepala, tangan, kaki","Kepala, muka, tangan, kaki"],"correctIndex":1,"explanation":"Allah berfirman dalam Surah al-Ma''idah 5:6 dengan urutan: muka → tangan hingga siku → sapu kepala → kaki hingga buku lali. Urutan ini (tertib) adalah wajib dalam mazhab Syafii."}',
 'Tertib mengajar kita untuk mengikut perintah Allah dengan betul, bukan sesuka hati. Adakah ada aspek kehidupanmu yang perlu kamu atur semula mengikut panduan Allah?',
 20),

(33,
 'Muwalat — Berterusan Tanpa Jeda Panjang',
 'الْمُوَالَاةُ فِي الْوُضُوءِ',
 'كَانَ يُوَالِي فِي وُضُوئِهِ وَلَا يُفَرِّقُ بَيْنَ أَعْضَائِهِ',
 'Kana yuwali fi wudu''ihi wala yufarriqu bayna a''da''ihi',
 'Baginda SAW melakukan wudu'' secara berterusan dan tidak memisah-misahkan antara anggotanya.',
 'Sunan Abu Dawud, Hadith 175; al-Daraqutni',
 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Wudu''', 'morning', 'Bersuci', '⏱️',
 'Muwalat bermaksud melakukan wudu'' secara berterusan — tidak berhenti lama antara anggota sehingga anggota sebelumnya kering. Jika berhenti terlalu lama dan anggota kering, perlu ulangi semula dari bahagian yang kering (mengikut mazhab Syafii). Fokus adalah kunci!',
 E'1. Mulakan wudu'' dengan bersungguh-sungguh\n2. Jangan berhenti terlalu lama antara setiap anggota\n3. Jika telefon berbunyi, boleh tunggu sebentar tetapi jangan biarkan anggota kering\n4. Teruskan dengan tertib dari awal hingga akhir\n5. Selesaikan dengan doa wudu''',
 '{"question":"Apakah yang dimaksudkan dengan muwalat dalam wudu''?","options":["Membasuh dengan banyak air","Melakukan wudu'' secara berterusan tanpa jeda panjang","Membasuh setiap anggota tiga kali","Memulakan dengan tangan kanan"],"correctIndex":1,"explanation":"Muwalat bermaksud melakukan wudu'' secara berterusan tanpa berhenti lama sehingga anggota yang sudah basah menjadi kering. Ini adalah syarat sah wudu'' mengikut pendapat ramai ulama."}',
 'Muwalat mengajar kita untuk fokus dan tidak bercerai-berai dalam ibadah. Adakah ibadah kamu selalu fokus atau sering terganggu? Bagaimana cara meningkatkan fokus?',
 15),

(34,
 'Isbagh — Menyempurnakan Wudu'' Dengan Teliti',
 'إِسْبَاغُ الْوُضُوءِ',
 'أَسْبِغُوا الْوُضُوءَ وَيْلٌ لِلْأَعْقَابِ مِنَ النَّارِ',
 'Asbigu''l-wudu''a waylun lil-a''qabi minan-nar',
 'Sempurnakanlah wudu'' kamu, celakalah tumit yang tidak kena air (dari azab neraka).',
 'Sahih al-Bukhari, Hadith 96; Sahih Muslim, Hadith 242',
 'Diriwayatkan oleh Abu Hurairah (RA)',
 'Wudu''', 'morning', 'Bersuci', '💯',
 'Rasulullah SAW memberi amaran keras tentang bahagian kecil yang tidak dibasuh dalam wudu'', terutama tumit. Isbagh bermaksud menyempurnakan wudu'' dengan memastikan seluruh had anggota benar-benar kena air. Jangan gopoh atau sambil lewa dalam ibadah!',
 E'Beri perhatian khusus semasa wudu'' kepada:\n1. Celah jari tangan dan kaki\n2. Kawasan tumit dan bawah kaki\n3. Bahagian belakang siku\n4. Celah janggut (jika ada)\n5. Pastikan air merata ke seluruh had anggota\n6. Lebih baik lambat tapi sempurna daripada cepat tapi tidak lengkap',
 '{"question":"Bahagian wudu'' manakah yang paling kerap diabaikan menurut hadith?","options":["Muka","Tangan","Tumit (bahagian belakang kaki)","Kepala"],"correctIndex":2,"explanation":"Rasulullah SAW memperingatkan secara khusus tentang ''waylun lil-a''qab'' (celakalah tumit) yang tidak dibasuh. Tumit adalah bahagian paling mudah terlepas basuh semasa wudu''. (Sahih al-Bukhari, Hadith 96)"}',
 'Amaran keras tentang perkara kecil mengajar kita untuk tidak sambil lewa dalam ibadah. Apakah pelajaran yang kamu ambil tentang pentingnya melakukan perkara dengan teliti dan sempurna?',
 20),

(35,
 'Tidak Membazir Air Semasa Wudu''',
 'النَّهْيُ عَنِ الْإِسْرَافِ فِي الْمَاءِ',
 'كَانَ يَتَوَضَّأُ بِالْمُدِّ وَيَغْتَسِلُ بِالصَّاعِ إِلَى خَمْسَةِ أَمْدَادٍ',
 'Kana yatawadda''u bil-muddi wa yaghtasilu bis-sa''i ila khamsati amdad',
 'Baginda SAW berwudu'' dengan (hanya) satu mud air dan mandi dengan satu sa'' hingga lima mud.',
 'Sahih al-Bukhari, Hadith 201; Sahih Muslim, Hadith 325',
 'Diriwayatkan oleh Anas ibn Malik (RA)',
 'Wudu''', 'morning', 'Bersuci', '🌊',
 'Satu mud air adalah lebih kurang 750ml — Rasulullah SAW berwudu'' hanya dengan segelas besar air. Ini mengajar kita untuk tidak membazir air walaupun sumber air melimpah. Air adalah nikmat Allah yang perlu dijaga. Membazir air adalah dilarang walaupun berwudu'' di tepi sungai.',
 E'1. Gunakan air sekadar yang diperlukan\n2. Matikan paip ketika menggosok atau mengusap\n3. Jangan biarkan air mengalir sia-sia\n4. Satu siram air yang cukup untuk setiap anggota sudah memadai\n5. Ingat: Rasulullah SAW berwudu'' hanya dengan 750ml air',
 '{"question":"Berapa banyak air yang digunakan Rasulullah SAW untuk berwudu''?","options":["Satu baldi penuh","Kira-kira satu mud (750ml)","Setengah baldi","Sepuluh liter"],"correctIndex":1,"explanation":"Rasulullah SAW berwudu'' dengan hanya satu mud (lebih kurang 750ml) air. Ini mengajar kita untuk tidak membazir air walaupun berwudu''. (Sahih al-Bukhari, Hadith 201)"}',
 'Rasulullah SAW berwudu'' dengan 750ml sahaja. Berapa banyak air yang kamu gunakan setiap hari? Apakah cara lain kamu boleh jimatkan sumber alam demi menjaga amanah Allah?',
 20),

(36,
 'Menyela Celah Jari Tangan dan Kaki',
 'تَخْلِيلُ الْأَصَابِعِ',
 'إِذَا تَوَضَّأْتَ فَخَلِّلْ أَصَابِعَ يَدَيْكَ وَرِجْلَيْكَ',
 'Idha tawadda''ta fakhal-lil asabi''a yadayka wa rijlayk',
 'Apabila kamu berwudu'', selakanlah celah jari tangan dan kaki kamu.',
 'Sunan al-Tirmidhi, Hadith 39; Sunan Abu Dawud, Hadith 142',
 'Diriwayatkan oleh Laqit ibn Saburah (RA)',
 'Wudu''', 'morning', 'Bersuci', '🤙',
 'Celah-celah jari adalah tempat yang mudah tertinggal semasa wudu''. Rasulullah SAW secara khusus mengarahkan kita untuk menyela jari tangan dan kaki. Untuk jari kaki, gunakan jari kelingking tangan kiri mulai dari jari kelingking kaki kanan.',
 E'Semasa membasuh tangan:\n1. Selepas membasuh, silangkan jari-jari antara satu sama lain\n\nSemasa membasuh kaki:\n2. Gunakan jari kelingking tangan kiri\n3. Masukkan dari bawah ke celah jari kaki\n4. Mulakan dari jari kelingking kaki kanan\n5. Akhiri di jari kelingking kaki kiri\n6. Pastikan air masuk ke setiap celah',
 '{"question":"Bagaimana cara menyela celah jari kaki dalam wudu''?","options":["Gosok bahagian atas kaki sahaja","Gunakan jari kelingking tangan kiri dari bawah ke celah jari","Guna sikat khas","Cukup tuang air dari atas"],"correctIndex":1,"explanation":"Rasulullah SAW mengajar cara menyela jari kaki menggunakan jari kelingking tangan kiri, dimasukkan dari bawah ke celah-celah jari kaki. Ini memastikan air masuk ke setiap celah. (Sunan al-Tirmidhi, Hadith 39)"}',
 'Perkara yang paling kecil pun ada cara yang betul dalam Islam. Apakah yang ini mengajar kamu tentang perhatian Islam kepada kebersihan yang menyeluruh?',
 15),

(37,
 'Mendahulukan Anggota Kanan Dalam Wudu''',
 'التَّيَمُّنُ فِي الطَّهَارَةِ',
 'كَانَ يُحِبُّ التَّيَمُّنَ مَا اسْتَطَاعَ فِي شَأْنِهِ كُلِّهِ',
 'Kana yuhibbut-tayammuna mas-tata''a fi sha''nihi kullihi',
 'Baginda SAW suka mendahulukan yang kanan sedaya mungkin dalam semua urusannya.',
 'Sahih al-Bukhari, Hadith 168', 'Diriwayatkan oleh ''A''ishah (RA)',
 'Wudu''', 'morning', 'Bersuci', '👍',
 'Prinsip tayammun (mendahulukan kanan) adalah ciri khas ibadah Islam. Dalam wudu'', tangan kanan dibasuh sebelum kiri, kaki kanan sebelum kiri. Ini mengajar kita untuk selalu mengutamakan yang terbaik dan mengikut sunnah Rasulullah SAW dalam setiap perkara.',
 E'Dalam wudu'', mendahulukan kanan bermaksud:\n1. Basuh tangan KANAN sebelum tangan kiri\n2. Basuh kaki KANAN sebelum kaki kiri\n\nPrinsip ini juga berlaku di luar wudu'':\n3. Pakai kasut — kaki kanan dahulu\n4. Masuk masjid — kaki kanan dahulu\n5. Makan — gunakan tangan kanan\n6. Beri sesuatu — dengan tangan kanan',
 '{"question":"Mengapakah kita mendahulukan anggota kanan dalam wudu''?","options":["Kerana kanan lebih kuat","Kerana mengikut sunnah Rasulullah SAW yang suka tayammun","Kerana kanan lebih mudah","Kerana kiri untuk perkara kotor sahaja"],"correctIndex":1,"explanation":"Rasulullah SAW suka mendahulukan sebelah kanan dalam semua perkara termasuk wudu''. Ini adalah sunnah tayammun yang menunjukkan penghormatan kepada yang lebih mulia. (Sahih al-Bukhari, Hadith 168)"}',
 'Cuba amalkan prinsip mendahulukan kanan hari ini — pakai kasut, masuk bilik, ambil sesuatu. Rasakan bagaimana sunnah kecil ini mendekatkan kamu kepada Rasulullah SAW.',
 15),

(38,
 'Doa Selepas Wudu''',
 'دُعَاءُ مَا بَعْدَ الْوُضُوءِ',
 'أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ',
 'Ashhadu an la ilaha illallahu wahdahu la sharika lah, wa ashhadu anna Muhammadan ''abduhu wa rasuluh. Allahumma j''alni minat-tawwabina waj''alni minal-mutatahhirin',
 'Aku bersaksi tiada tuhan selain Allah, Esa tiada sekutu bagi-Nya, dan aku bersaksi Muhammad adalah hamba dan rasul-Nya. Ya Allah, jadikanlah aku dari kalangan orang yang bertaubat dan dari kalangan orang yang sentiasa bersuci.',
 'Sahih Muslim, Hadith 234; Sunan al-Tirmidhi, Hadith 55',
 'Diriwayatkan oleh ''Umar ibn al-Khattab (RA)',
 'Wudu''', 'morning', 'Bersuci', '🤲',
 'Membaca doa ini selepas wudu'' membuka lapan pintu syurga untuk dipilih! Hadith menyebut: "Sesiapa yang berwudu'' dengan sempurna kemudian membaca syahadah ini, dibuka baginya lapan pintu syurga." Ganjaran yang luar biasa bagi amalan yang mudah dilakukan setiap hari!',
 E'1. Selepas selesai wudu''\n2. Angkat pandangan ke langit\n3. Baca shahada: Ashhadu an la ilaha illallah...\n4. Sambung: Allahumma j''alni minat-tawwabin...\n5. Boleh tambah: Subhanakallahumma wa bihamdika...\n6. Terus bersedia untuk solat',
 '{"question":"Apakah ganjaran bagi orang yang membaca doa selepas wudu'' dengan sempurna?","options":["Mendapat 100 pahala","Dibuka lapan pintu syurga","Diampunkan semua dosa","Mendapat darjat wali"],"correctIndex":1,"explanation":"Hadith menyebut bahawa sesiapa yang berwudu'' dengan sempurna dan membaca syahadah selepasnya akan dibuka lapan pintu syurga untuk dipilih mana satu. (Sahih Muslim, Hadith 234)"}',
 'Lapan pintu syurga dibuka dengan doa ringkas selepas wudu''! Allah sangat pemurah. Adakah ini memotivasikan kamu untuk berwudu'' dengan lebih sempurna mulai hari ini?',
 25),

(39,
 'Solat Dua Rakaat Sunat Selepas Wudu''',
 'صَلَاةُ رَكْعَتَيْنِ بَعْدَ الْوُضُوءِ',
 'مَنْ تَوَضَّأَ نَحْوَ وُضُوئِي هَذَا ثُمَّ صَلَّى رَكْعَتَيْنِ لَا يُحَدِّثُ فِيهِمَا نَفْسَهُ غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
 'Man tawadda''a nahwa wudu''i hadha thumma salla rak''atayni la yuhaddithu fihima nafsahu ghufira lahu ma taqaddama min dhambihi',
 'Sesiapa yang berwudu'' seperti wudu''ku ini, kemudian solat dua rakaat tanpa berbicara dengan dirinya sendiri dalam solat, diampunkan baginya dosa-dosa yang telah lalu.',
 'Sahih al-Bukhari, Hadith 159; Sahih Muslim, Hadith 226',
 'Diriwayatkan oleh ''Uthman ibn ''Affan (RA)',
 'Wudu''', 'morning', 'Bersuci', '🙏',
 'Solat dua rakaat selepas wudu'' adalah sunnah yang sangat berbaloi! Ganjaran yang dijanjikan adalah pengampunan dosa-dosa yang lalu. Sayyiduna Bilal ibn Rabah RA mengamalkan solat sunat wudu'' dan Rasulullah SAW mendengar bunyi kasutnya di syurga ketika Isra'' Mi''raj.',
 E'1. Selesai berwudu'' dengan sempurna\n2. Baca doa selepas wudu''\n3. Cari tempat yang bersih dan tenang\n4. Niat: Sahaja aku solat sunat wudu'' 2 rakaat kerana Allah\n5. Solat 2 rakaat dengan khusyuk dan fokus\n6. Jangan biarkan lamunan mengganggu solat',
 '{"question":"Apakah ganjaran solat dua rakaat selepas wudu'' mengikut hadith?","options":["Mendapat pahala 100 solat","Diampunkan dosa-dosa yang lalu","Dijamin masuk syurga langsung","Mendapat maqam wali"],"correctIndex":1,"explanation":"Rasulullah SAW bersabda sesiapa yang berwudu'' seperti baginda kemudian solat dua rakaat dengan khusyuk, Allah mengampunkan dosa-dosanya yang lalu. Bilal RA adalah pengamal setia sunat wudu''. (Sahih al-Bukhari, Hadith 159)"}',
 'Solat dua rakaat boleh menghapuskan dosa-dosa lalu! Allah sangat Maha Pengampun. Mulai hari ini, cuba amalkan solat sunat wudu'' setiap kali selepas berwudu''. Rasai perbezaannya!',
 25)

ON CONFLICT (id) DO NOTHING;
