// KSSM syllabus metadata used by both the app and the lesson-library generation script.
// Keep this file free of React/browser imports so Node.js scripts can import it directly.

export interface KssmChapter {
  id: string;
  title: string;     // English title
  titleBM: string;   // Bahasa Malaysia title
}

export interface KssmSubject {
  id: string;
  name: string;      // English name
  nameBM: string;    // BM name
  forMode: 'both' | 'muslim' | 'universal';
  chapters: Record<string, KssmChapter[]>; // key = T1 | T2 | T3 | T4 | T5
}

export const KSSM_SUBJECTS: KssmSubject[] = [
  {
    id: 'matematik',
    name: 'Mathematics',
    nameBM: 'Matematik',
    forMode: 'both',
    chapters: {
      T1: [
        { id: 'mt1-1', title: 'Rational Numbers', titleBM: 'Nombor Nisbah' },
        { id: 'mt1-2', title: 'Factors and Multiples', titleBM: 'Faktor dan Gandaan' },
        { id: 'mt1-3', title: 'Squares, Square Roots, Cubes & Cube Roots', titleBM: 'Kuasa Dua, Punca Kuasa Dua, Kuasa Tiga & Punca Kuasa Tiga' },
        { id: 'mt1-4', title: 'Ratios, Rates and Proportions', titleBM: 'Nisbah, Kadar dan Kadaran' },
        { id: 'mt1-5', title: 'Algebraic Expressions', titleBM: 'Ungkapan Algebra' },
        { id: 'mt1-6', title: 'Linear Equations', titleBM: 'Persamaan Linear' },
        { id: 'mt1-7', title: 'Linear Inequalities', titleBM: 'Ketaksamaan Linear' },
        { id: 'mt1-8', title: 'Lines and Angles', titleBM: 'Garis dan Sudut' },
        { id: 'mt1-9', title: 'Basic Polygons', titleBM: 'Poligon Asas' },
        { id: 'mt1-10', title: 'Perimeter and Area', titleBM: 'Perimeter dan Luas' },
        { id: 'mt1-11', title: 'Introduction to Set', titleBM: 'Pengenalan Set' },
        { id: 'mt1-12', title: 'Data Handling', titleBM: 'Pengendalian Data' },
        { id: 'mt1-13', title: 'The Pythagoras Theorem', titleBM: 'Teorem Pythagoras' },
      ],
      T2: [
        { id: 'mt2-1', title: 'Patterns and Sequences', titleBM: 'Pola dan Jujukan' },
        { id: 'mt2-2', title: 'Factorisation and Algebraic Fractions', titleBM: 'Pemfaktoran dan Pecahan Algebra' },
        { id: 'mt2-3', title: 'Algebraic Formulae', titleBM: 'Formula Algebra' },
        { id: 'mt2-4', title: 'Polygon', titleBM: 'Poligon' },
        { id: 'mt2-5', title: 'Circles', titleBM: 'Bulatan' },
        { id: 'mt2-6', title: 'Three-Dimensional Geometric Shapes', titleBM: 'Bentuk Geometri Tiga Dimensi' },
        { id: 'mt2-7', title: 'Coordinates', titleBM: 'Koordinat' },
        { id: 'mt2-8', title: 'Graphs of Functions', titleBM: 'Graf Fungsi' },
        { id: 'mt2-9', title: 'Speed and Acceleration', titleBM: 'Laju dan Pecutan' },
        { id: 'mt2-10', title: 'Gradient of a Straight Line', titleBM: 'Kecerunan Garis Lurus' },
        { id: 'mt2-11', title: 'Isometric Transformations', titleBM: 'Transformasi Isometri' },
        { id: 'mt2-12', title: 'Measures of Central Tendencies', titleBM: 'Sukatan Kecenderungan Memusat' },
        { id: 'mt2-13', title: 'Simple Probability', titleBM: 'Kebarangkalian Mudah' },
      ],
      T3: [
        { id: 'mt3-1', title: 'Indices', titleBM: 'Indeks' },
        { id: 'mt3-2', title: 'Standard Form', titleBM: 'Bentuk Piawai' },
        { id: 'mt3-3', title: 'Consumer Mathematics: Savings, Investments, Credit & Debt', titleBM: 'Matematik Pengguna: Simpanan, Pelaburan, Kredit & Hutang' },
        { id: 'mt3-4', title: 'Scale Drawings', titleBM: 'Lukisan Berskala' },
        { id: 'mt3-5', title: 'Trigonometric Ratios', titleBM: 'Nisbah Trigonometri' },
        { id: 'mt3-6', title: 'Angles and Tangents of Circles', titleBM: 'Sudut dan Tangen Bulatan' },
        { id: 'mt3-7', title: 'Plans and Elevations', titleBM: 'Pelan dan Dongakan' },
        { id: 'mt3-8', title: 'Loci in Two Dimensions', titleBM: 'Lokus dalam Dua Dimensi' },
        { id: 'mt3-9', title: 'Straight Lines', titleBM: 'Garis Lurus' },
      ],
      T4: [
        { id: 'mt4-1', title: 'Quadratic Functions & Equations in One Variable', titleBM: 'Fungsi Kuadratik & Persamaan dalam Satu Pemboleh Ubah' },
        { id: 'mt4-2', title: 'Number Bases', titleBM: 'Asas Nombor' },
        { id: 'mt4-3', title: 'Logical Reasoning', titleBM: 'Penaakulan Logik' },
        { id: 'mt4-4', title: 'Operations on Sets', titleBM: 'Operasi ke atas Set' },
        { id: 'mt4-5', title: 'Network in Graph Theory', titleBM: 'Rangkaian dalam Teori Graf' },
        { id: 'mt4-6', title: 'Linear Inequalities in Two Variables', titleBM: 'Ketaksamaan Linear dalam Dua Pemboleh Ubah' },
        { id: 'mt4-7', title: 'Graphs of Motion', titleBM: 'Graf Gerakan' },
        { id: 'mt4-8', title: 'Measures of Dispersion for Ungrouped Data', titleBM: 'Sukatan Serakan bagi Data Tak Terkumpul' },
        { id: 'mt4-9', title: 'Probability of Combined Events', titleBM: 'Kebarangkalian Peristiwa Bergabung' },
        { id: 'mt4-10', title: 'Consumer Mathematics: Financial Management', titleBM: 'Matematik Pengguna: Pengurusan Kewangan' },
      ],
      T5: [
        { id: 'mt5-1', title: 'Variation', titleBM: 'Ubahan' },
        { id: 'mt5-2', title: 'Matrices', titleBM: 'Matriks' },
        { id: 'mt5-3', title: 'Consumer Mathematics: Insurance & Takaful', titleBM: 'Matematik Pengguna: Insurans & Takaful' },
        { id: 'mt5-4', title: 'Consumer Mathematics: Taxation', titleBM: 'Matematik Pengguna: Percukaian' },
        { id: 'mt5-5', title: 'Congruency, Enlargement & Combined Transformations', titleBM: 'Kekongruenan, Pembesaran & Gabungan Transformasi' },
        { id: 'mt5-6', title: 'Ratios & Graphs of Trigonometric Functions', titleBM: 'Nisbah & Graf Fungsi Trigonometri' },
        { id: 'mt5-7', title: 'Measures of Dispersion for Grouped Data', titleBM: 'Sukatan Serakan bagi Data Terkumpul' },
        { id: 'mt5-8', title: 'Mathematical Modeling', titleBM: 'Pemodelan Matematik' },
      ],
    },
  },
  {
    id: 'sains',
    name: 'Science',
    nameBM: 'Sains',
    forMode: 'both',
    chapters: {
      T1: [
        { id: 'sc1-1', title: 'Introduction to Science', titleBM: 'Pengenalan kepada Sains' },
        { id: 'sc1-2', title: 'Cell as a Unit of Life', titleBM: 'Sel sebagai Unit Kehidupan' },
        { id: 'sc1-3', title: 'Matter', titleBM: 'Jirim' },
        { id: 'sc1-4', title: 'Atomic Structure', titleBM: 'Struktur Atom' },
        { id: 'sc1-5', title: 'The Periodic Table', titleBM: 'Jadual Berkala' },
        { id: 'sc1-6', title: 'Density', titleBM: 'Ketumpatan' },
        { id: 'sc1-7', title: 'The Variety of Resources on Earth', titleBM: 'Kepelbagaian Sumber di Bumi' },
      ],
      T2: [
        { id: 'sc2-1', title: 'Biodiversity', titleBM: 'Biodiversiti' },
        { id: 'sc2-2', title: 'Nutrition', titleBM: 'Nutrisi' },
        { id: 'sc2-3', title: 'Ecosystem', titleBM: 'Ekosistem' },
        { id: 'sc2-4', title: 'Water and Solution', titleBM: 'Air dan Larutan' },
        { id: 'sc2-5', title: 'Acids and Bases', titleBM: 'Asid dan Bes' },
        { id: 'sc2-6', title: 'Force and Motion', titleBM: 'Daya dan Gerakan' },
        { id: 'sc2-7', title: 'Heat', titleBM: 'Haba' },
        { id: 'sc2-8', title: 'Electricity and Magnetism', titleBM: 'Elektrik dan Kemagnetan' },
      ],
      T3: [
        { id: 'sc3-1', title: 'Respiration', titleBM: 'Respirasi' },
        { id: 'sc3-2', title: 'Blood Circulation and Transport', titleBM: 'Peredaran Darah dan Pengangkutan' },
        { id: 'sc3-3', title: 'Excretion', titleBM: 'Perkumuhan' },
        { id: 'sc3-4', title: 'Reproduction', titleBM: 'Pembiakan' },
        { id: 'sc3-5', title: 'Growth', titleBM: 'Pertumbuhan' },
        { id: 'sc3-6', title: 'Land and its Resources', titleBM: 'Tanah dan Sumbernya' },
        { id: 'sc3-7', title: 'Electricity & Magnetism', titleBM: 'Elektrik & Kemagnetan' },
        { id: 'sc3-8', title: 'Light & Optics', titleBM: 'Cahaya & Optik' },
        { id: 'sc3-9', title: 'Sound', titleBM: 'Bunyi' },
        { id: 'sc3-10', title: 'Space Exploration', titleBM: 'Penerokaan Angkasa' },
      ],
      T4: [
        { id: 'sc4-1', title: 'Stimuli and Responses', titleBM: 'Rangsangan dan Tindak Balas' },
        { id: 'sc4-2', title: 'Homeostasis in Humans', titleBM: 'Homeostasis dalam Manusia' },
        { id: 'sc4-3', title: 'Inheritance', titleBM: 'Pewarisan' },
        { id: 'sc4-4', title: 'Waves, Light and Sound', titleBM: 'Gelombang, Cahaya dan Bunyi' },
        { id: 'sc4-5', title: 'Electricity and Electronics', titleBM: 'Elektrik dan Elektronik' },
      ],
      T5: [
        { id: 'sc5-1', title: 'Microorganisms and Their Effects on Living Things', titleBM: 'Mikroorganisma dan Kesannya kepada Hidupan' },
        { id: 'sc5-2', title: 'Nutrition and Food Production', titleBM: 'Nutrisi dan Pengeluaran Makanan' },
        { id: 'sc5-3', title: 'Endangered Ecosystem', titleBM: 'Ekosistem Terancam' },
        { id: 'sc5-4', title: 'Energy & Chemical Changes', titleBM: 'Tenaga & Perubahan Kimia' },
        { id: 'sc5-5', title: 'Nuclear Energy', titleBM: 'Tenaga Nuklear' },
        { id: 'sc5-6', title: 'Consumer & Industrial Technology', titleBM: 'Teknologi Pengguna & Industri' },
      ],
    },
  },
  {
    id: 'bahasa-melayu',
    name: 'Bahasa Melayu',
    nameBM: 'Bahasa Melayu',
    forMode: 'both',
    chapters: {
      T1: [
        { id: 'bm1-1', title: 'Comprehension Skills', titleBM: 'Kemahiran Membaca dan Memahami' },
        { id: 'bm1-2', title: 'Essay Writing - Narrative', titleBM: 'Penulisan Karangan - Naratif' },
        { id: 'bm1-3', title: 'Grammar - Word Classes', titleBM: 'Tatabahasa - Golongan Kata' },
        { id: 'bm1-4', title: 'KOMSAS - Poems & Short Stories', titleBM: 'KOMSAS - Sajak & Cerpen' },
        { id: 'bm1-5', title: 'Summary Writing', titleBM: 'Penulisan Rumusan' },
      ],
      T2: [
        { id: 'bm2-1', title: 'Essay Writing - Descriptive', titleBM: 'Penulisan Karangan - Deskriptif' },
        { id: 'bm2-2', title: 'Grammar - Sentence Structure', titleBM: 'Tatabahasa - Ayat Tunggal & Ayat Majmuk' },
        { id: 'bm2-3', title: 'KOMSAS - Drama & Pantun', titleBM: 'KOMSAS - Drama & Pantun' },
        { id: 'bm2-4', title: 'Formal Letter Writing', titleBM: 'Penulisan Surat Rasmi' },
        { id: 'bm2-5', title: 'Idioms & Proverbs', titleBM: 'Peribahasa & Simpulan Bahasa' },
      ],
      T3: [
        { id: 'bm3-1', title: 'Essay Writing - Argumentative', titleBM: 'Penulisan Karangan - Perbahasan' },
        { id: 'bm3-2', title: 'Grammar - Morphology', titleBM: 'Tatabahasa - Morfologi (Imbuhan)' },
        { id: 'bm3-3', title: 'KOMSAS - Novel', titleBM: 'KOMSAS - Novel' },
        { id: 'bm3-4', title: 'Report Writing', titleBM: 'Penulisan Laporan' },
        { id: 'bm3-5', title: 'Listening & Speaking Skills', titleBM: 'Kemahiran Mendengar & Bertutur' },
      ],
      T4: [
        { id: 'bm4-1', title: 'SPM Essay - Section A (Directed)', titleBM: 'Karangan SPM - Bahagian A (Berpandu)' },
        { id: 'bm4-2', title: 'SPM Essay - Section B (Open)', titleBM: 'Karangan SPM - Bahagian B (Terbuka)' },
        { id: 'bm4-3', title: 'Advanced Grammar & Error Correction', titleBM: 'Tatabahasa Lanjutan & Pembetulan Kesalahan' },
        { id: 'bm4-4', title: 'KOMSAS SPM - Anthology', titleBM: 'KOMSAS SPM - Antologi' },
        { id: 'bm4-5', title: 'SPM Summary Techniques', titleBM: 'Teknik Rumusan SPM' },
        { id: 'bm4-6', title: 'Comprehension - SPM Format', titleBM: 'Pemahaman - Format SPM' },
      ],
      T5: [
        { id: 'bm5-1', title: 'SPM Essay Mastery', titleBM: 'Penguasaan Karangan SPM' },
        { id: 'bm5-2', title: 'KOMSAS SPM - Novel & Anthology Revision', titleBM: 'KOMSAS SPM - Ulangkaji Novel & Antologi' },
        { id: 'bm5-3', title: 'Grammar Intensive Review', titleBM: 'Ulangkaji Intensif Tatabahasa' },
        { id: 'bm5-4', title: 'Oral Test Preparation', titleBM: 'Persediaan Ujian Lisan' },
        { id: 'bm5-5', title: 'SPM Full Paper Practice', titleBM: 'Latihan Kertas Penuh SPM' },
      ],
    },
  },
  {
    id: 'english',
    name: 'English',
    nameBM: 'Bahasa Inggeris',
    forMode: 'both',
    chapters: {
      T1: [
        { id: 'en1-1', title: 'Reading Comprehension - Fiction & Non-Fiction', titleBM: 'Pemahaman Bacaan - Fiksyen & Bukan Fiksyen' },
        { id: 'en1-2', title: 'Grammar - Tenses (Present & Past)', titleBM: 'Tatabahasa - Kala (Kini & Lampau)' },
        { id: 'en1-3', title: 'Writing - Descriptive Paragraph', titleBM: 'Penulisan - Perenggan Deskriptif' },
        { id: 'en1-4', title: 'Literature - Short Stories', titleBM: 'Kesusasteraan - Cerpen' },
        { id: 'en1-5', title: 'Vocabulary Building', titleBM: 'Pembinaan Kosa Kata' },
      ],
      T2: [
        { id: 'en2-1', title: 'Grammar - Continuous & Perfect Tenses', titleBM: 'Tatabahasa - Kala Berterusan & Sempurna' },
        { id: 'en2-2', title: 'Writing - Narrative Essay', titleBM: 'Penulisan - Karangan Naratif' },
        { id: 'en2-3', title: 'Literature - Poems', titleBM: 'Kesusasteraan - Puisi' },
        { id: 'en2-4', title: 'Informal Letter & Email Writing', titleBM: 'Penulisan Surat Tak Rasmi & E-mel' },
        { id: 'en2-5', title: 'Speaking - Conversations & Discussions', titleBM: 'Pertuturan - Perbualan & Perbincangan' },
      ],
      T3: [
        { id: 'en3-1', title: 'Grammar - Conditionals & Passive Voice', titleBM: 'Tatabahasa - Ayat Bersyarat & Ayat Pasif' },
        { id: 'en3-2', title: 'Writing - Formal Letter & Report', titleBM: 'Penulisan - Surat Rasmi & Laporan' },
        { id: 'en3-3', title: 'Literature - Drama & Novel', titleBM: 'Kesusasteraan - Drama & Novel' },
        { id: 'en3-4', title: 'Reading - Critical Thinking', titleBM: 'Bacaan - Pemikiran Kritis' },
        { id: 'en3-5', title: 'Summary Writing Skills', titleBM: 'Kemahiran Penulisan Rumusan' },
      ],
      T4: [
        { id: 'en4-1', title: 'SPM Writing - Directed & Continuous', titleBM: 'Penulisan SPM - Berpandu & Berterusan' },
        { id: 'en4-2', title: 'SPM Literature Component', titleBM: 'Komponen Kesusasteraan SPM' },
        { id: 'en4-3', title: 'Advanced Grammar - Complex Sentences', titleBM: 'Tatabahasa Lanjutan - Ayat Kompleks' },
        { id: 'en4-4', title: 'Comprehension - SPM Format', titleBM: 'Pemahaman - Format SPM' },
        { id: 'en4-5', title: 'Summary - SPM Techniques', titleBM: 'Rumusan - Teknik SPM' },
      ],
      T5: [
        { id: 'en5-1', title: 'SPM Essay Mastery - All Formats', titleBM: 'Penguasaan Karangan SPM - Semua Format' },
        { id: 'en5-2', title: 'Literature Revision - Poems, Stories, Drama, Novel', titleBM: 'Ulangkaji Sastera - Puisi, Cerpen, Drama, Novel' },
        { id: 'en5-3', title: 'Grammar Intensive Review', titleBM: 'Ulangkaji Intensif Tatabahasa' },
        { id: 'en5-4', title: 'Speaking Test Preparation', titleBM: 'Persediaan Ujian Lisan' },
        { id: 'en5-5', title: 'SPM Full Paper Practice', titleBM: 'Latihan Kertas Penuh SPM' },
      ],
    },
  },
  {
    id: 'sejarah',
    name: 'History',
    nameBM: 'Sejarah',
    forMode: 'both',
    chapters: {
      T1: [
        { id: 'sj1-1', title: 'How to Study History', titleBM: 'Cara Belajar Sejarah' },
        { id: 'sj1-2', title: 'Early Malay Government System', titleBM: 'Sistem Pemerintahan Melayu Awal' },
        { id: 'sj1-3', title: 'The Malay Sultanate of Melaka', titleBM: 'Kesultanan Melayu Melaka' },
        { id: 'sj1-4', title: 'Malay Sultanate Administration System', titleBM: 'Sistem Pentadbiran Kesultanan Melayu' },
        { id: 'sj1-5', title: 'Trade & Economy of the Malay Sultanate', titleBM: 'Perdagangan & Ekonomi Kesultanan Melayu' },
        { id: 'sj1-6', title: 'Society & Culture of the Malay Sultanate', titleBM: 'Masyarakat & Kebudayaan Kesultanan Melayu' },
      ],
      T2: [
        { id: 'sj2-1', title: 'European Powers in Southeast Asia', titleBM: 'Kuasa Eropah di Asia Tenggara' },
        { id: 'sj2-2', title: 'Colonial Era in Malaya', titleBM: 'Zaman Penjajahan di Tanah Melayu' },
        { id: 'sj2-3', title: 'British Colonisation of Sabah & Sarawak', titleBM: 'Penjajahan British di Sabah & Sarawak' },
        { id: 'sj2-4', title: 'Rise of Nationalism', titleBM: 'Kebangkitan Nasionalisme' },
        { id: 'sj2-5', title: 'Japanese Occupation', titleBM: 'Pendudukan Jepun' },
        { id: 'sj2-6', title: 'Path to Independence', titleBM: 'Jalan ke Arah Kemerdekaan' },
      ],
      T3: [
        { id: 'sj3-1', title: 'Government & Country Administration', titleBM: 'Pemerintahan & Pentadbiran Negara' },
        { id: 'sj3-2', title: 'Federal Constitution', titleBM: 'Perlembagaan Persekutuan' },
        { id: 'sj3-3', title: 'Formation of Malaysia', titleBM: 'Pembentukan Malaysia' },
        { id: 'sj3-4', title: 'National Development', titleBM: 'Pembangunan Negara' },
        { id: 'sj3-5', title: 'National Unity & Integration', titleBM: 'Perpaduan & Integrasi Nasional' },
      ],
      T4: [
        { id: 'sj4-1', title: 'Early Civilisations of the World', titleBM: 'Tamadun Awal Dunia' },
        { id: 'sj4-2', title: 'The Malay World Before the Arrival of Islam', titleBM: 'Dunia Melayu Sebelum Kedatangan Islam' },
        { id: 'sj4-3', title: 'Islam and its Spread in the Malay World', titleBM: 'Islam dan Penyebarannya di Alam Melayu' },
        { id: 'sj4-4', title: 'The Malay Sultanate of Melaka (Advanced)', titleBM: 'Kesultanan Melayu Melaka (Lanjutan)' },
        { id: 'sj4-5', title: 'Threats to Malay Sovereignty', titleBM: 'Ancaman kepada Kedaulatan Melayu' },
        { id: 'sj4-6', title: 'British Intervention & Impact', titleBM: 'Campur Tangan & Kesan Penjajahan British' },
        { id: 'sj4-7', title: 'National Awakening in Malaya', titleBM: 'Kebangkitan Kebangsaan di Tanah Melayu' },
      ],
      T5: [
        { id: 'sj5-1', title: 'Malayan Union & Independence Struggle', titleBM: 'Malayan Union & Perjuangan Kemerdekaan' },
        { id: 'sj5-2', title: 'Formation of Malaysia', titleBM: 'Pembentukan Malaysia' },
        { id: 'sj5-3', title: 'Building a Sovereign Nation', titleBM: 'Membina Negara Berdaulat' },
        { id: 'sj5-4', title: 'Malaysia in the International Arena', titleBM: 'Malaysia di Persada Antarabangsa' },
        { id: 'sj5-5', title: 'National Development & Vision 2020', titleBM: 'Pembangunan Negara & Wawasan 2020' },
        { id: 'sj5-6', title: 'Patriotism & National Identity', titleBM: 'Patriotisme & Identiti Kebangsaan' },
      ],
    },
  },
  {
    id: 'add-math',
    name: 'Additional Mathematics',
    nameBM: 'Matematik Tambahan',
    forMode: 'both',
    chapters: {
      T1: [], T2: [], T3: [],
      T4: [
        { id: 'am4-1', title: 'Functions', titleBM: 'Fungsi' },
        { id: 'am4-2', title: 'Quadratic Functions', titleBM: 'Fungsi Kuadratik' },
        { id: 'am4-3', title: 'Systems of Equations', titleBM: 'Sistem Persamaan' },
        { id: 'am4-4', title: 'Indices, Surds & Logarithms', titleBM: 'Indeks, Surd & Logaritma' },
        { id: 'am4-5', title: 'Progressions', titleBM: 'Janjang' },
        { id: 'am4-6', title: 'Linear Law', titleBM: 'Hukum Linear' },
        { id: 'am4-7', title: 'Coordinate Geometry', titleBM: 'Geometri Koordinat' },
        { id: 'am4-8', title: 'Vectors', titleBM: 'Vektor' },
        { id: 'am4-9', title: 'Solution of Triangles', titleBM: 'Penyelesaian Segitiga' },
        { id: 'am4-10', title: 'Index Numbers', titleBM: 'Nombor Indeks' },
      ],
      T5: [
        { id: 'am5-1', title: 'Circular Measure', titleBM: 'Sukatan Membulat' },
        { id: 'am5-2', title: 'Differentiation', titleBM: 'Pembezaan' },
        { id: 'am5-3', title: 'Integration', titleBM: 'Pengamiran' },
        { id: 'am5-4', title: 'Permutations & Combinations', titleBM: 'Pilih Atur & Gabungan' },
        { id: 'am5-5', title: 'Probability Distribution', titleBM: 'Taburan Kebarangkalian' },
        { id: 'am5-6', title: 'Trigonometric Functions', titleBM: 'Fungsi Trigonometri' },
        { id: 'am5-7', title: 'Linear Programming', titleBM: 'Pengaturcaraan Linear' },
        { id: 'am5-8', title: 'Kinematics of Linear Motion', titleBM: 'Kinematik Gerakan Linear' },
      ],
    },
  },
  {
    id: 'physics',
    name: 'Physics',
    nameBM: 'Fizik',
    forMode: 'both',
    chapters: {
      T1: [], T2: [], T3: [],
      T4: [
        { id: 'ph4-1', title: 'Measurement', titleBM: 'Pengukuran' },
        { id: 'ph4-2', title: 'Force and Motion I', titleBM: 'Daya dan Gerakan I' },
        { id: 'ph4-3', title: 'Gravitation', titleBM: 'Graviti' },
        { id: 'ph4-4', title: 'Heat', titleBM: 'Haba' },
        { id: 'ph4-5', title: 'Waves', titleBM: 'Gelombang' },
        { id: 'ph4-6', title: 'Light and Optics', titleBM: 'Cahaya dan Optik' },
      ],
      T5: [
        { id: 'ph5-1', title: 'Force and Motion II', titleBM: 'Daya dan Gerakan II' },
        { id: 'ph5-2', title: 'Pressure', titleBM: 'Tekanan' },
        { id: 'ph5-3', title: 'Electricity', titleBM: 'Elektrik' },
        { id: 'ph5-4', title: 'Electromagnetism', titleBM: 'Elektromagnet' },
        { id: 'ph5-5', title: 'Electronics', titleBM: 'Elektronik' },
        { id: 'ph5-6', title: 'Nuclear Physics', titleBM: 'Fizik Nuklear' },
        { id: 'ph5-7', title: 'Quantum Physics', titleBM: 'Fizik Kuantum' },
      ],
    },
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    nameBM: 'Kimia',
    forMode: 'both',
    chapters: {
      T1: [], T2: [], T3: [],
      T4: [
        { id: 'ch4-1', title: 'Matter & Atomic Structure', titleBM: 'Jirim & Struktur Atom' },
        { id: 'ch4-2', title: 'The Periodic Table', titleBM: 'Jadual Berkala' },
        { id: 'ch4-3', title: 'Chemical Formulae & Equations', titleBM: 'Formula & Persamaan Kimia' },
        { id: 'ch4-4', title: 'The Mole Concept', titleBM: 'Konsep Mol' },
        { id: 'ch4-5', title: 'Chemical Bonds', titleBM: 'Ikatan Kimia' },
        { id: 'ch4-6', title: 'Acids, Bases, and Salts', titleBM: 'Asid, Bes, dan Garam' },
        { id: 'ch4-7', title: 'Rate of Reaction', titleBM: 'Kadar Tindak Balas' },
      ],
      T5: [
        { id: 'ch5-1', title: 'Oxidation & Reduction', titleBM: 'Pengoksidaan & Penurunan' },
        { id: 'ch5-2', title: 'Thermochemistry', titleBM: 'Termokimia' },
        { id: 'ch5-3', title: 'Carbon Compounds', titleBM: 'Sebatian Karbon' },
        { id: 'ch5-4', title: 'Manufactured Substances', titleBM: 'Bahan Buatan dalam Industri' },
        { id: 'ch5-5', title: 'Electrochemistry', titleBM: 'Elektrokimia' },
      ],
    },
  },
  {
    id: 'biology',
    name: 'Biology',
    nameBM: 'Biologi',
    forMode: 'both',
    chapters: {
      T1: [], T2: [], T3: [],
      T4: [
        { id: 'bi4-1', title: 'Cell Biology & Organisation', titleBM: 'Biologi Sel & Organisasi' },
        { id: 'bi4-2', title: 'Movement of Substances', titleBM: 'Pergerakan Bahan' },
        { id: 'bi4-3', title: 'Chemical Composition in Cell', titleBM: 'Komposisi Kimia dalam Sel' },
        { id: 'bi4-4', title: 'Cell Division', titleBM: 'Pembahagian Sel' },
        { id: 'bi4-5', title: 'Nutrition', titleBM: 'Nutrisi' },
        { id: 'bi4-6', title: 'Respiration', titleBM: 'Respirasi' },
        { id: 'bi4-7', title: 'Transportation', titleBM: 'Pengangkutan' },
      ],
      T5: [
        { id: 'bi5-1', title: 'Homeostasis', titleBM: 'Homeostasis' },
        { id: 'bi5-2', title: 'Support & Locomotion', titleBM: 'Sokongan & Gerakan' },
        { id: 'bi5-3', title: 'Coordination & Response', titleBM: 'Koordinasi & Gerak Balas' },
        { id: 'bi5-4', title: 'Reproduction', titleBM: 'Pembiakan' },
        { id: 'bi5-5', title: 'Inheritance', titleBM: 'Pewarisan' },
        { id: 'bi5-6', title: 'Variation', titleBM: 'Variasi' },
      ],
    },
  },
  {
    id: 'geography',
    name: 'Geography',
    nameBM: 'Geografi',
    forMode: 'both',
    chapters: {
      T1: [
        { id: 'ge1-1', title: 'Introduction to Geography', titleBM: 'Pengenalan Geografi' },
        { id: 'ge1-2', title: 'The Earth', titleBM: 'Planet Bumi' },
        { id: 'ge1-3', title: 'Maps and Directions', titleBM: 'Peta dan Arah' },
      ],
      T2: [
        { id: 'ge2-1', title: 'Weather and Climate', titleBM: 'Cuaca dan Iklim' },
        { id: 'ge2-2', title: 'Landforms', titleBM: 'Bentuk Muka Bumi' },
        { id: 'ge2-3', title: 'Population', titleBM: 'Penduduk' },
      ],
      T3: [
        { id: 'ge3-1', title: 'Resources and Economic Activities', titleBM: 'Sumber dan Aktiviti Ekonomi' },
        { id: 'ge3-2', title: 'Urbanisation', titleBM: 'Pembandaran' },
        { id: 'ge3-3', title: 'Transportation', titleBM: 'Pengangkutan' },
      ],
      T4: [], T5: [],
    },
  },
  {
    id: 'economics',
    name: 'Basic Economics',
    nameBM: 'Ekonomi Asas',
    forMode: 'both',
    chapters: {
      T1: [], T2: [], T3: [],
      T4: [
        { id: 'ec4-1', title: 'Introduction to Economics', titleBM: 'Pengenalan Ekonomi' },
        { id: 'ec4-2', title: 'Scarcity and Choice', titleBM: 'Kekurangan dan Pilihan' },
        { id: 'ec4-3', title: 'Demand and Supply', titleBM: 'Permintaan dan Penawaran' },
        { id: 'ec4-4', title: 'Market Structure', titleBM: 'Struktur Pasaran' },
        { id: 'ec4-5', title: 'Elasticity', titleBM: 'Keanjalan' },
      ],
      T5: [
        { id: 'ec5-1', title: 'National Income', titleBM: 'Pendapatan Negara' },
        { id: 'ec5-2', title: 'Money and Banking', titleBM: 'Wang dan Perbankan' },
        { id: 'ec5-3', title: 'Government Fiscal Policy', titleBM: 'Dasar Fiskal Kerajaan' },
        { id: 'ec5-4', title: 'International Trade', titleBM: 'Perdagangan Antarabangsa' },
        { id: 'ec5-5', title: 'Economic Development', titleBM: 'Pembangunan Ekonomi' },
      ],
    },
  },
  {
    id: 'pend-islam',
    name: 'Pendidikan Islam',
    nameBM: 'Pendidikan Islam',
    forMode: 'muslim',
    chapters: {
      T1: [
        { id: 'pi1-1', title: 'Aqidah - Beriman kepada Allah', titleBM: 'Aqidah - Beriman kepada Allah' },
        { id: 'pi1-2', title: 'Ibadah - Solat Fardhu', titleBM: 'Ibadah - Solat Fardhu' },
        { id: 'pi1-3', title: 'Sirah - Rasulullah SAW', titleBM: 'Sirah - Rasulullah SAW' },
        { id: 'pi1-4', title: 'Akhlak - Adab Mulia', titleBM: 'Akhlak - Adab Mulia' },
        { id: 'pi1-5', title: 'Tilawah al-Quran', titleBM: 'Tilawah al-Quran' },
      ],
      T2: [
        { id: 'pi2-1', title: 'Aqidah - Sifat Allah', titleBM: 'Aqidah - Sifat Allah' },
        { id: 'pi2-2', title: 'Ibadah - Puasa & Zakat', titleBM: 'Ibadah - Puasa & Zakat' },
        { id: 'pi2-3', title: 'Sirah - Khulafa al-Rasyidin', titleBM: 'Sirah - Khulafa al-Rasyidin' },
        { id: 'pi2-4', title: 'Akhlak - Adab Bermasyarakat', titleBM: 'Akhlak - Adab Bermasyarakat' },
      ],
      T3: [
        { id: 'pi3-1', title: 'Aqidah - Iman kepada Hari Akhirat', titleBM: 'Aqidah - Iman kepada Hari Akhirat' },
        { id: 'pi3-2', title: 'Ibadah - Haji & Korban', titleBM: 'Ibadah - Haji & Korban' },
        { id: 'pi3-3', title: 'Muamalat - Jual Beli Islam', titleBM: 'Muamalat - Jual Beli Islam' },
      ],
      T4: [
        { id: 'pi4-1', title: 'Aqidah - Qada & Qadar', titleBM: 'Aqidah - Qada & Qadar' },
        { id: 'pi4-2', title: 'Fiqh Munakahat', titleBM: 'Fiqh Munakahat' },
        { id: 'pi4-3', title: 'Tamadun Islam', titleBM: 'Tamadun Islam' },
        { id: 'pi4-4', title: 'Hadis - 40 Hadis Pilihan', titleBM: 'Hadis - 40 Hadis Pilihan' },
      ],
      T5: [
        { id: 'pi5-1', title: 'Aqidah - Islam & Sains', titleBM: 'Aqidah - Islam & Sains' },
        { id: 'pi5-2', title: 'Fiqh Jenayah & Kekeluargaan', titleBM: 'Fiqh Jenayah & Kekeluargaan' },
        { id: 'pi5-3', title: 'Dakwah & Kepimpinan Islam', titleBM: 'Dakwah & Kepimpinan Islam' },
      ],
    },
  },
  {
    id: 'pend-moral',
    name: 'Moral Education',
    nameBM: 'Pendidikan Moral',
    forMode: 'universal',
    chapters: {
      T1: [
        { id: 'pm1-1', title: 'Respect & Responsibility', titleBM: 'Menghormati & Tanggungjawab' },
        { id: 'pm1-2', title: 'Honesty & Integrity', titleBM: 'Kejujuran & Integriti' },
        { id: 'pm1-3', title: 'Kindness & Empathy', titleBM: 'Kebaikan Hati & Empati' },
      ],
      T2: [
        { id: 'pm2-1', title: 'Integrity & Honesty', titleBM: 'Integriti & Kejujuran' },
        { id: 'pm2-2', title: 'Compassion & Empathy', titleBM: 'Belas Kasihan & Empati' },
        { id: 'pm2-3', title: 'National Unity', titleBM: 'Perpaduan Nasional' },
      ],
      T3: [
        { id: 'pm3-1', title: 'Environmental Ethics', titleBM: 'Etika Alam Sekitar' },
        { id: 'pm3-2', title: 'Digital Citizenship', titleBM: 'Kewarganegaraan Digital' },
        { id: 'pm3-3', title: 'Community Service', titleBM: 'Khidmat Masyarakat' },
      ],
      T4: [
        { id: 'pm4-1', title: 'Human Rights & Justice', titleBM: 'Hak Asasi & Keadilan' },
        { id: 'pm4-2', title: 'Ethical Decision Making', titleBM: 'Membuat Keputusan Beretika' },
        { id: 'pm4-3', title: 'Global Citizenship', titleBM: 'Kewarganegaraan Global' },
      ],
      T5: [
        { id: 'pm5-1', title: 'Moral Philosophy', titleBM: 'Falsafah Moral' },
        { id: 'pm5-2', title: 'Social Responsibility', titleBM: 'Tanggungjawab Sosial' },
        { id: 'pm5-3', title: 'Leadership & Ethics', titleBM: 'Kepimpinan & Etika' },
      ],
    },
  },
  {
    id: 'perakaunan',
    name: 'Principles of Accounting',
    nameBM: 'Prinsip Perakaunan',
    forMode: 'universal',
    chapters: {
      T1: [], T2: [], T3: [],
      T4: [
        { id: 'pa4-1', title: 'Introduction to Accounting', titleBM: 'Pengenalan Perakaunan' },
        { id: 'pa4-2', title: 'Classification of Accounts', titleBM: 'Pengelasan Akaun' },
        { id: 'pa4-3', title: 'Documents as Source of Information', titleBM: 'Dokumen Sebagai Sumber Maklumat' },
        { id: 'pa4-4', title: 'Journals', titleBM: 'Jurnal' },
        { id: 'pa4-5', title: 'Ledger', titleBM: 'Lejar' },
        { id: 'pa4-6', title: 'Trial Balance', titleBM: 'Imbangan Duga' },
        { id: 'pa4-7', title: 'Financial Statements of Sole Proprietorship', titleBM: 'Penyata Kewangan Milikan Tunggal' },
      ],
      T5: [
        { id: 'pa5-1', title: 'Adjustments in Financial Statements', titleBM: 'Pelarasan Penyata Kewangan' },
        { id: 'pa5-2', title: 'Financial Statements of Partnership', titleBM: 'Penyata Kewangan Perkongsian' },
        { id: 'pa5-3', title: 'Company Accounts', titleBM: 'Akaun Syarikat' },
        { id: 'pa5-4', title: 'Cash Flow Statement', titleBM: 'Penyata Aliran Tunai' },
        { id: 'pa5-5', title: 'Financial Ratios', titleBM: 'Nisbah Kewangan' },
        { id: 'pa5-6', title: 'Cost Accounting', titleBM: 'Perakaunan Kos' },
      ],
    },
  },
  {
    id: 'sains-komputer',
    name: 'Computer Science',
    nameBM: 'Sains Komputer',
    forMode: 'universal',
    chapters: {
      T1: [
        { id: 'sk1-1', title: 'Computational Thinking', titleBM: 'Pemikiran Komputasional' },
        { id: 'sk1-2', title: 'Representation of Data', titleBM: 'Perwakilan Data' },
        { id: 'sk1-3', title: 'Algorithms', titleBM: 'Algoritma' },
      ],
      T2: [
        { id: 'sk2-1', title: 'Data & Information', titleBM: 'Data dan Maklumat' },
        { id: 'sk2-2', title: 'Introduction to Programming', titleBM: 'Pengenalan Pengaturcaraan' },
        { id: 'sk2-3', title: 'Flowcharts & Pseudocode', titleBM: 'Carta Alir dan Pseudokod' },
      ],
      T3: [
        { id: 'sk3-1', title: 'Computer System', titleBM: 'Sistem Komputer' },
        { id: 'sk3-2', title: 'Computer Networking', titleBM: 'Rangkaian Komputer' },
        { id: 'sk3-3', title: 'Interactive Application Development', titleBM: 'Pembangunan Aplikasi Interaktif' },
      ],
      T4: [
        { id: 'sk4-1', title: 'Database Management', titleBM: 'Pengurusan Pangkalan Data' },
        { id: 'sk4-2', title: 'Programming Fundamentals', titleBM: 'Asas Pengaturcaraan' },
        { id: 'sk4-3', title: 'Web Application Development', titleBM: 'Pembangunan Aplikasi Web' },
      ],
      T5: [
        { id: 'sk5-1', title: 'Emerging Technologies', titleBM: 'Teknologi Baharu Muncul' },
        { id: 'sk5-2', title: 'Advanced Programming', titleBM: 'Pengaturcaraan Lanjutan' },
        { id: 'sk5-3', title: 'Innovation & Entrepreneurship in IT', titleBM: 'Inovasi dan Keusahawanan dalam IT' },
      ],
    },
  },
];

// Total chapter count (excluding empty tingkatan entries)
export function countAllChapters(): number {
  return KSSM_SUBJECTS.reduce((total, subject) =>
    total + Object.values(subject.chapters).reduce((t, chs) => t + chs.length, 0), 0);
}
