// Auto-generated Quran Surah Index
// Total: 114 Surahs, 6,236 Ayat

export interface SurahMeta {
  number: number;
  nameArabic: string;
  nameMalay: string;
  nameEnglish: string;
  meaning: string;
  totalAyat: number;
  revelationType: 'Makkiyyah' | 'Madaniyyah';
  juzuk: string;
}

export const SURAH_INDEX: SurahMeta[] = [
  { number: 1, nameArabic: "الفاتحة", nameMalay: "Al-Fatihah", nameEnglish: "The Opening", meaning: "Pembukaan", totalAyat: 7, revelationType: "Makkiyyah", juzuk: "1" },
  { number: 2, nameArabic: "البقرة", nameMalay: "Al-Baqarah", nameEnglish: "The Cow", meaning: "Lembu Betina", totalAyat: 286, revelationType: "Madaniyyah", juzuk: "1-3" },
  { number: 3, nameArabic: "آل عمران", nameMalay: "Ali 'Imran", nameEnglish: "The Family of Imran", meaning: "Keluarga Imran", totalAyat: 200, revelationType: "Madaniyyah", juzuk: "3-4" },
  { number: 4, nameArabic: "النساء", nameMalay: "An-Nisa'", nameEnglish: "The Women", meaning: "Wanita", totalAyat: 176, revelationType: "Madaniyyah", juzuk: "4-6" },
  { number: 5, nameArabic: "المائدة", nameMalay: "Al-Ma'idah", nameEnglish: "The Table Spread", meaning: "Hidangan", totalAyat: 120, revelationType: "Madaniyyah", juzuk: "6-7" },
  { number: 6, nameArabic: "الأنعام", nameMalay: "Al-An'am", nameEnglish: "The Cattle", meaning: "Binatang Ternakan", totalAyat: 165, revelationType: "Makkiyyah", juzuk: "7-8" },
  { number: 7, nameArabic: "الأعراف", nameMalay: "Al-A'raf", nameEnglish: "The Heights", meaning: "Tempat Tertinggi", totalAyat: 206, revelationType: "Makkiyyah", juzuk: "8-9" },
  { number: 8, nameArabic: "الأنفال", nameMalay: "Al-Anfal", nameEnglish: "The Spoils of War", meaning: "Rampasan Perang", totalAyat: 75, revelationType: "Madaniyyah", juzuk: "9-10" },
  { number: 9, nameArabic: "التوبة", nameMalay: "At-Taubah", nameEnglish: "The Repentance", meaning: "Taubat", totalAyat: 129, revelationType: "Madaniyyah", juzuk: "10-11" },
  { number: 10, nameArabic: "يونس", nameMalay: "Yunus", nameEnglish: "Jonah", meaning: "Nabi Yunus", totalAyat: 109, revelationType: "Makkiyyah", juzuk: "11" },
  { number: 11, nameArabic: "هود", nameMalay: "Hud", nameEnglish: "Hud", meaning: "Nabi Hud", totalAyat: 123, revelationType: "Makkiyyah", juzuk: "11-12" },
  { number: 12, nameArabic: "يوسف", nameMalay: "Yusuf", nameEnglish: "Joseph", meaning: "Nabi Yusuf", totalAyat: 111, revelationType: "Makkiyyah", juzuk: "12-13" },
  { number: 13, nameArabic: "الرعد", nameMalay: "Ar-Ra'd", nameEnglish: "The Thunder", meaning: "Guruh", totalAyat: 43, revelationType: "Madaniyyah", juzuk: "13" },
  { number: 14, nameArabic: "إبراهيم", nameMalay: "Ibrahim", nameEnglish: "Abraham", meaning: "Nabi Ibrahim", totalAyat: 52, revelationType: "Makkiyyah", juzuk: "13" },
  { number: 15, nameArabic: "الحجر", nameMalay: "Al-Hijr", nameEnglish: "The Rocky Tract", meaning: "Batu Gunung", totalAyat: 99, revelationType: "Makkiyyah", juzuk: "14" },
  { number: 16, nameArabic: "النحل", nameMalay: "An-Nahl", nameEnglish: "The Bee", meaning: "Lebah", totalAyat: 128, revelationType: "Makkiyyah", juzuk: "14" },
  { number: 17, nameArabic: "الإسراء", nameMalay: "Al-Isra'", nameEnglish: "The Night Journey", meaning: "Perjalanan Malam", totalAyat: 111, revelationType: "Makkiyyah", juzuk: "15" },
  { number: 18, nameArabic: "الكهف", nameMalay: "Al-Kahf", nameEnglish: "The Cave", meaning: "Gua", totalAyat: 110, revelationType: "Makkiyyah", juzuk: "15-16" },
  { number: 19, nameArabic: "مريم", nameMalay: "Maryam", nameEnglish: "Mary", meaning: "Maryam", totalAyat: 98, revelationType: "Makkiyyah", juzuk: "16" },
  { number: 20, nameArabic: "طه", nameMalay: "Ta Ha", nameEnglish: "Ta Ha", meaning: "Ta Ha", totalAyat: 135, revelationType: "Makkiyyah", juzuk: "16" },
  { number: 21, nameArabic: "الأنبياء", nameMalay: "Al-Anbiya'", nameEnglish: "The Prophets", meaning: "Para Nabi", totalAyat: 112, revelationType: "Makkiyyah", juzuk: "17" },
  { number: 22, nameArabic: "الحج", nameMalay: "Al-Hajj", nameEnglish: "The Pilgrimage", meaning: "Haji", totalAyat: 78, revelationType: "Madaniyyah", juzuk: "17" },
  { number: 23, nameArabic: "المؤمنون", nameMalay: "Al-Mu'minun", nameEnglish: "The Believers", meaning: "Orang Mukmin", totalAyat: 118, revelationType: "Makkiyyah", juzuk: "18" },
  { number: 24, nameArabic: "النور", nameMalay: "An-Nur", nameEnglish: "The Light", meaning: "Cahaya", totalAyat: 64, revelationType: "Madaniyyah", juzuk: "18" },
  { number: 25, nameArabic: "الفرقان", nameMalay: "Al-Furqan", nameEnglish: "The Criterion", meaning: "Pembeza", totalAyat: 77, revelationType: "Makkiyyah", juzuk: "18-19" },
  { number: 26, nameArabic: "الشعراء", nameMalay: "Asy-Syu'ara'", nameEnglish: "The Poets", meaning: "Penyair", totalAyat: 227, revelationType: "Makkiyyah", juzuk: "19" },
  { number: 27, nameArabic: "النمل", nameMalay: "An-Naml", nameEnglish: "The Ant", meaning: "Semut", totalAyat: 93, revelationType: "Makkiyyah", juzuk: "19-20" },
  { number: 28, nameArabic: "القصص", nameMalay: "Al-Qasas", nameEnglish: "The Stories", meaning: "Kisah-kisah", totalAyat: 88, revelationType: "Makkiyyah", juzuk: "20" },
  { number: 29, nameArabic: "العنكبوت", nameMalay: "Al-'Ankabut", nameEnglish: "The Spider", meaning: "Labah-labah", totalAyat: 69, revelationType: "Makkiyyah", juzuk: "20-21" },
  { number: 30, nameArabic: "الروم", nameMalay: "Ar-Rum", nameEnglish: "The Romans", meaning: "Bangsa Rom", totalAyat: 60, revelationType: "Makkiyyah", juzuk: "21" },
  { number: 31, nameArabic: "لقمان", nameMalay: "Luqman", nameEnglish: "Luqman", meaning: "Luqman", totalAyat: 34, revelationType: "Makkiyyah", juzuk: "21" },
  { number: 32, nameArabic: "السجدة", nameMalay: "As-Sajdah", nameEnglish: "The Prostration", meaning: "Sujud", totalAyat: 30, revelationType: "Makkiyyah", juzuk: "21" },
  { number: 33, nameArabic: "الأحزاب", nameMalay: "Al-Ahzab", nameEnglish: "The Combined Forces", meaning: "Puak-puak Bersekutu", totalAyat: 73, revelationType: "Madaniyyah", juzuk: "21-22" },
  { number: 34, nameArabic: "سبأ", nameMalay: "Saba'", nameEnglish: "Sheba", meaning: "Kaum Saba'", totalAyat: 54, revelationType: "Makkiyyah", juzuk: "22" },
  { number: 35, nameArabic: "فاطر", nameMalay: "Fatir", nameEnglish: "The Originator", meaning: "Pencipta", totalAyat: 45, revelationType: "Makkiyyah", juzuk: "22" },
  { number: 36, nameArabic: "يس", nameMalay: "Ya Sin", nameEnglish: "Ya Sin", meaning: "Ya Sin", totalAyat: 83, revelationType: "Makkiyyah", juzuk: "22-23" },
  { number: 37, nameArabic: "الصافات", nameMalay: "As-Saffat", nameEnglish: "Those Ranged in Ranks", meaning: "Berbaris-baris", totalAyat: 182, revelationType: "Makkiyyah", juzuk: "23" },
  { number: 38, nameArabic: "ص", nameMalay: "Sad", nameEnglish: "Sad", meaning: "Sad", totalAyat: 88, revelationType: "Makkiyyah", juzuk: "23" },
  { number: 39, nameArabic: "الزمر", nameMalay: "Az-Zumar", nameEnglish: "The Crowds", meaning: "Rombongan", totalAyat: 75, revelationType: "Makkiyyah", juzuk: "23-24" },
  { number: 40, nameArabic: "غافر", nameMalay: "Ghafir", nameEnglish: "The Forgiver", meaning: "Yang Mengampuni", totalAyat: 85, revelationType: "Makkiyyah", juzuk: "24" },
  { number: 41, nameArabic: "فصلت", nameMalay: "Fussilat", nameEnglish: "Explained in Detail", meaning: "Yang Dijelaskan", totalAyat: 54, revelationType: "Makkiyyah", juzuk: "24-25" },
  { number: 42, nameArabic: "الشورى", nameMalay: "Asy-Syura", nameEnglish: "The Consultation", meaning: "Musyawarah", totalAyat: 53, revelationType: "Makkiyyah", juzuk: "25" },
  { number: 43, nameArabic: "الزخرف", nameMalay: "Az-Zukhruf", nameEnglish: "The Gold Adornments", meaning: "Perhiasan Emas", totalAyat: 89, revelationType: "Makkiyyah", juzuk: "25" },
  { number: 44, nameArabic: "الدخان", nameMalay: "Ad-Dukhan", nameEnglish: "The Smoke", meaning: "Asap", totalAyat: 59, revelationType: "Makkiyyah", juzuk: "25" },
  { number: 45, nameArabic: "الجاثية", nameMalay: "Al-Jasiyah", nameEnglish: "The Kneeling", meaning: "Berlutut", totalAyat: 37, revelationType: "Makkiyyah", juzuk: "25" },
  { number: 46, nameArabic: "الأحقاف", nameMalay: "Al-Ahqaf", nameEnglish: "The Sand Dunes", meaning: "Bukit Pasir", totalAyat: 35, revelationType: "Makkiyyah", juzuk: "26" },
  { number: 47, nameArabic: "محمد", nameMalay: "Muhammad", nameEnglish: "Muhammad", meaning: "Nabi Muhammad", totalAyat: 38, revelationType: "Madaniyyah", juzuk: "26" },
  { number: 48, nameArabic: "الفتح", nameMalay: "Al-Fath", nameEnglish: "The Victory", meaning: "Kemenangan", totalAyat: 29, revelationType: "Madaniyyah", juzuk: "26" },
  { number: 49, nameArabic: "الحجرات", nameMalay: "Al-Hujurat", nameEnglish: "The Rooms", meaning: "Bilik-bilik", totalAyat: 18, revelationType: "Madaniyyah", juzuk: "26" },
  { number: 50, nameArabic: "ق", nameMalay: "Qaf", nameEnglish: "Qaf", meaning: "Qaf", totalAyat: 45, revelationType: "Makkiyyah", juzuk: "26" },
  { number: 51, nameArabic: "الذاريات", nameMalay: "Az-Zariyat", nameEnglish: "The Scattering Winds", meaning: "Angin Yang Menerbangkan", totalAyat: 60, revelationType: "Makkiyyah", juzuk: "26-27" },
  { number: 52, nameArabic: "الطور", nameMalay: "At-Tur", nameEnglish: "The Mount", meaning: "Bukit Tursina", totalAyat: 49, revelationType: "Makkiyyah", juzuk: "27" },
  { number: 53, nameArabic: "النجم", nameMalay: "An-Najm", nameEnglish: "The Star", meaning: "Bintang", totalAyat: 62, revelationType: "Makkiyyah", juzuk: "27" },
  { number: 54, nameArabic: "القمر", nameMalay: "Al-Qamar", nameEnglish: "The Moon", meaning: "Bulan", totalAyat: 55, revelationType: "Makkiyyah", juzuk: "27" },
  { number: 55, nameArabic: "الرحمن", nameMalay: "Ar-Rahman", nameEnglish: "The Most Merciful", meaning: "Yang Maha Pemurah", totalAyat: 78, revelationType: "Madaniyyah", juzuk: "27" },
  { number: 56, nameArabic: "الواقعة", nameMalay: "Al-Waqi'ah", nameEnglish: "The Event", meaning: "Hari Kiamat", totalAyat: 96, revelationType: "Makkiyyah", juzuk: "27" },
  { number: 57, nameArabic: "الحديد", nameMalay: "Al-Hadid", nameEnglish: "The Iron", meaning: "Besi", totalAyat: 29, revelationType: "Madaniyyah", juzuk: "27" },
  { number: 58, nameArabic: "المجادلة", nameMalay: "Al-Mujadalah", nameEnglish: "The Dispute", meaning: "Perempuan Yang Membantah", totalAyat: 22, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 59, nameArabic: "الحشر", nameMalay: "Al-Hasyr", nameEnglish: "The Gathering", meaning: "Pengusiran", totalAyat: 24, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 60, nameArabic: "الممتحنة", nameMalay: "Al-Mumtahanah", nameEnglish: "The Examined One", meaning: "Perempuan Yang Diuji", totalAyat: 13, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 61, nameArabic: "الصف", nameMalay: "As-Saff", nameEnglish: "The Ranks", meaning: "Barisan", totalAyat: 14, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 62, nameArabic: "الجمعة", nameMalay: "Al-Jumu'ah", nameEnglish: "Friday", meaning: "Hari Jumaat", totalAyat: 11, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 63, nameArabic: "المنافقون", nameMalay: "Al-Munafiqun", nameEnglish: "The Hypocrites", meaning: "Orang Munafik", totalAyat: 11, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 64, nameArabic: "التغابن", nameMalay: "At-Taghabun", nameEnglish: "The Mutual Disillusion", meaning: "Hari Kekecewaan", totalAyat: 18, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 65, nameArabic: "الطلاق", nameMalay: "At-Talaq", nameEnglish: "The Divorce", meaning: "Talak", totalAyat: 12, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 66, nameArabic: "التحريم", nameMalay: "At-Tahrim", nameEnglish: "The Prohibition", meaning: "Pengharaman", totalAyat: 12, revelationType: "Madaniyyah", juzuk: "28" },
  { number: 67, nameArabic: "الملك", nameMalay: "Al-Mulk", nameEnglish: "The Sovereignty", meaning: "Kerajaan", totalAyat: 30, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 68, nameArabic: "القلم", nameMalay: "Al-Qalam", nameEnglish: "The Pen", meaning: "Pena", totalAyat: 52, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 69, nameArabic: "الحاقة", nameMalay: "Al-Haqqah", nameEnglish: "The Reality", meaning: "Hari Kiamat", totalAyat: 52, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 70, nameArabic: "المعارج", nameMalay: "Al-Ma'arij", nameEnglish: "The Ascending Stairways", meaning: "Tempat Naik", totalAyat: 44, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 71, nameArabic: "نوح", nameMalay: "Nuh", nameEnglish: "Noah", meaning: "Nabi Nuh", totalAyat: 28, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 72, nameArabic: "الجن", nameMalay: "Al-Jinn", nameEnglish: "The Jinn", meaning: "Jin", totalAyat: 28, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 73, nameArabic: "المزمل", nameMalay: "Al-Muzzammil", nameEnglish: "The Enshrouded One", meaning: "Orang Yang Berselimut", totalAyat: 20, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 74, nameArabic: "المدثر", nameMalay: "Al-Muddassir", nameEnglish: "The Cloaked One", meaning: "Orang Yang Berselubung", totalAyat: 56, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 75, nameArabic: "القيامة", nameMalay: "Al-Qiyamah", nameEnglish: "The Resurrection", meaning: "Hari Kiamat", totalAyat: 40, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 76, nameArabic: "الإنسان", nameMalay: "Al-Insan", nameEnglish: "Man", meaning: "Manusia", totalAyat: 31, revelationType: "Madaniyyah", juzuk: "29" },
  { number: 77, nameArabic: "المرسلات", nameMalay: "Al-Mursalat", nameEnglish: "Those Sent Forth", meaning: "Yang Diutus", totalAyat: 50, revelationType: "Makkiyyah", juzuk: "29" },
  { number: 78, nameArabic: "النبأ", nameMalay: "An-Naba'", nameEnglish: "The Great News", meaning: "Berita Besar", totalAyat: 40, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 79, nameArabic: "النازعات", nameMalay: "An-Nazi'at", nameEnglish: "Those Who Pull Out", meaning: "Malaikat Pencabut Nyawa", totalAyat: 46, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 80, nameArabic: "عبس", nameMalay: "'Abasa", nameEnglish: "He Frowned", meaning: "Bermuka Masam", totalAyat: 42, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 81, nameArabic: "التكوير", nameMalay: "At-Takwir", nameEnglish: "The Overthrowing", meaning: "Menggulung", totalAyat: 29, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 82, nameArabic: "الإنفطار", nameMalay: "Al-Infitar", nameEnglish: "The Cleaving", meaning: "Terbelah", totalAyat: 19, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 83, nameArabic: "المطففين", nameMalay: "Al-Mutaffifin", nameEnglish: "The Defrauding", meaning: "Orang Yang Curang", totalAyat: 36, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 84, nameArabic: "الانشقاق", nameMalay: "Al-Insyiqaq", nameEnglish: "The Splitting Open", meaning: "Terbelah", totalAyat: 25, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 85, nameArabic: "البروج", nameMalay: "Al-Buruj", nameEnglish: "The Constellations", meaning: "Gugusan Bintang", totalAyat: 22, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 86, nameArabic: "الطارق", nameMalay: "At-Tariq", nameEnglish: "The Night Comer", meaning: "Bintang Yang Mengetuk", totalAyat: 17, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 87, nameArabic: "الأعلى", nameMalay: "Al-A'la", nameEnglish: "The Most High", meaning: "Yang Maha Tinggi", totalAyat: 19, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 88, nameArabic: "الغاشية", nameMalay: "Al-Ghasyiyah", nameEnglish: "The Overwhelming", meaning: "Hari Pembalasan", totalAyat: 26, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 89, nameArabic: "الفجر", nameMalay: "Al-Fajr", nameEnglish: "The Dawn", meaning: "Fajar", totalAyat: 30, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 90, nameArabic: "البلد", nameMalay: "Al-Balad", nameEnglish: "The City", meaning: "Negeri", totalAyat: 20, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 91, nameArabic: "الشمس", nameMalay: "Asy-Syams", nameEnglish: "The Sun", meaning: "Matahari", totalAyat: 15, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 92, nameArabic: "الليل", nameMalay: "Al-Lail", nameEnglish: "The Night", meaning: "Malam", totalAyat: 21, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 93, nameArabic: "الضحى", nameMalay: "Ad-Duha", nameEnglish: "The Morning Hours", meaning: "Waktu Dhuha", totalAyat: 11, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 94, nameArabic: "الشرح", nameMalay: "Asy-Syarh", nameEnglish: "The Relief", meaning: "Kelapangan", totalAyat: 8, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 95, nameArabic: "التين", nameMalay: "At-Tin", nameEnglish: "The Fig", meaning: "Buah Tin", totalAyat: 8, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 96, nameArabic: "العلق", nameMalay: "Al-'Alaq", nameEnglish: "The Clot", meaning: "Segumpal Darah", totalAyat: 19, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 97, nameArabic: "القدر", nameMalay: "Al-Qadr", nameEnglish: "The Power", meaning: "Kemuliaan", totalAyat: 5, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 98, nameArabic: "البينة", nameMalay: "Al-Bayyinah", nameEnglish: "The Clear Proof", meaning: "Bukti Yang Nyata", totalAyat: 8, revelationType: "Madaniyyah", juzuk: "30" },
  { number: 99, nameArabic: "الزلزلة", nameMalay: "Az-Zalzalah", nameEnglish: "The Earthquake", meaning: "Gempa Bumi", totalAyat: 8, revelationType: "Madaniyyah", juzuk: "30" },
  { number: 100, nameArabic: "العاديات", nameMalay: "Al-'Adiyat", nameEnglish: "The Chargers", meaning: "Kuda Perang", totalAyat: 11, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 101, nameArabic: "القارعة", nameMalay: "Al-Qari'ah", nameEnglish: "The Calamity", meaning: "Hari Kiamat", totalAyat: 11, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 102, nameArabic: "التكاثر", nameMalay: "At-Takasur", nameEnglish: "The Rivalry", meaning: "Bermegah-megah", totalAyat: 8, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 103, nameArabic: "العصر", nameMalay: "Al-'Asr", nameEnglish: "The Time", meaning: "Masa", totalAyat: 3, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 104, nameArabic: "الهمزة", nameMalay: "Al-Humazah", nameEnglish: "The Slanderer", meaning: "Pengumpat", totalAyat: 9, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 105, nameArabic: "الفيل", nameMalay: "Al-Fil", nameEnglish: "The Elephant", meaning: "Gajah", totalAyat: 5, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 106, nameArabic: "قريش", nameMalay: "Quraisy", nameEnglish: "Quraysh", meaning: "Kaum Quraisy", totalAyat: 4, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 107, nameArabic: "الماعون", nameMalay: "Al-Ma'un", nameEnglish: "The Small Kindnesses", meaning: "Bantuan", totalAyat: 7, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 108, nameArabic: "الكوثر", nameMalay: "Al-Kausar", nameEnglish: "The Abundance", meaning: "Nikmat Yang Banyak", totalAyat: 3, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 109, nameArabic: "الكافرون", nameMalay: "Al-Kafirun", nameEnglish: "The Disbelievers", meaning: "Orang Kafir", totalAyat: 6, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 110, nameArabic: "النصر", nameMalay: "An-Nasr", nameEnglish: "The Divine Support", meaning: "Pertolongan", totalAyat: 3, revelationType: "Madaniyyah", juzuk: "30" },
  { number: 111, nameArabic: "المسد", nameMalay: "Al-Masad", nameEnglish: "The Palm Fiber", meaning: "Tali Dari Sabut", totalAyat: 5, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 112, nameArabic: "الإخلاص", nameMalay: "Al-Ikhlas", nameEnglish: "The Sincerity", meaning: "Keikhlasan", totalAyat: 4, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 113, nameArabic: "الفلق", nameMalay: "Al-Falaq", nameEnglish: "The Daybreak", meaning: "Waktu Subuh", totalAyat: 5, revelationType: "Makkiyyah", juzuk: "30" },
  { number: 114, nameArabic: "الناس", nameMalay: "An-Nas", nameEnglish: "Mankind", meaning: "Manusia", totalAyat: 6, revelationType: "Makkiyyah", juzuk: "30" },
];

export const getTotalAyat = (): number => {
  return SURAH_INDEX.reduce((sum, s) => sum + s.totalAyat, 0);
};

export const getSurahByNumber = (num: number): SurahMeta | undefined => {
  return SURAH_INDEX.find(s => s.number === num);
};
