import React, { useState, useEffect } from 'react';
import type { DashboardMode } from '../../types';
import StudyPlannerSetup from './StudyPlannerSetup';
import WeeklyPlanView from './WeeklyPlanView';
import PlannerInsights from './PlannerInsights';
import {
  getStudyProfile,
  getActivePlan,
  markTaskComplete,
  adjustPlan,
  saveStudyPlan,
  type WeeklyPlan,
  type StudyPlan,
  type StudyProgress,
  getPlanProgress,
} from '../../services/studyPlannerAgent';

// ═══════════════════════════════════════════════════════════
// STUDY PLANNER PAGE — Full-page study planner view
// Shows setup if no profile, otherwise weekly plan + insights
// ═══════════════════════════════════════════════════════════

interface Props {
  dashboardMode: DashboardMode;
}

const StudyPlannerPage: React.FC<Props> = ({ dashboardMode }) => {
  const isMuslim = dashboardMode === 'muslim';
  const t = (bm: string, en: string) => (isMuslim ? bm : en);

  const [hasProfile, setHasProfile] = useState<boolean | null>(null);
  const [plan, setPlan] = useState<WeeklyPlan | null>(null);
  const [planId, setPlanId] = useState<string | null>(null);
  const [completedTasks, setCompletedTasks] = useState<Set<string>>(new Set());
  const [loading, setLoading] = useState(true);
  const [replanLoading, setReplanLoading] = useState(false);
  const [showScoreModal, setShowScoreModal] = useState<{ subject: string; chapter: string } | null>(null);
  const [scoreInput, setScoreInput] = useState(70);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const profile = await getStudyProfile();
      if (!profile) {
        setHasProfile(false);
        setLoading(false);
        return;
      }

      setHasProfile(true);
      const activePlan = await getActivePlan();
      if (activePlan) {
        setPlan(activePlan.plan_data);
        setPlanId(activePlan.id);

        // Load completed tasks
        const progress = await getPlanProgress(activePlan.id);
        const done = new Set<string>();
        for (const p of progress) {
          if (p.completed) done.add(`${p.subject}::${p.chapter}`);
        }
        setCompletedTasks(done);
      }
    } catch {
      // Fail gracefully
    } finally {
      setLoading(false);
    }
  };

  const handleSetupComplete = (newPlan: WeeklyPlan, _profileId: string, newPlanId: string) => {
    setHasProfile(true);
    setPlan(newPlan);
    setPlanId(newPlanId);
    setCompletedTasks(new Set());
  };

  const handleMarkComplete = (subject: string, chapter: string) => {
    setShowScoreModal({ subject, chapter });
    setScoreInput(70);
  };

  const confirmComplete = async () => {
    if (!showScoreModal || !planId) return;
    const { subject, chapter } = showScoreModal;
    const key = `${subject}::${chapter}`;

    try {
      await markTaskComplete(planId, subject, chapter, scoreInput);
      setCompletedTasks((prev) => new Set([...prev, key]));
    } catch {
      // Ignore
    }
    setShowScoreModal(null);
  };

  const handleReplan = async () => {
    if (!planId) return;
    setReplanLoading(true);
    try {
      const newPlanData = await adjustPlan(planId);
      // Get profile_id from current plan
      const activePlan = await getActivePlan();
      const profileId = activePlan?.profile_id;
      if (profileId) {
        const weekNum = (activePlan?.week_number || 0) + 1;
        const newPlanId = await saveStudyPlan(profileId, newPlanData, weekNum);
        setPlan(newPlanData);
        setPlanId(newPlanId);
        setCompletedTasks(new Set());
      }
    } catch {
      // Ignore
    } finally {
      setReplanLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="animate-spin w-8 h-8 border-2 border-[var(--primary)] border-t-transparent rounded-full" />
      </div>
    );
  }

  // Show setup if no profile
  if (!hasProfile) {
    return <StudyPlannerSetup dashboardMode={dashboardMode} onComplete={handleSetupComplete} />;
  }

  return (
    <div className="space-y-6">
      {/* Action Bar */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-[var(--foreground)]">
            {t('Perancang Ulangkaji AI', 'AI Study Planner')}
          </h2>
          <p className="text-xs text-[var(--muted)]">
            {t('Jadual dijana oleh AI agent berdasarkan profil kamu.', 'Schedule generated by AI agent based on your profile.')}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => { setHasProfile(false); }}
            className="px-3 py-1.5 rounded-lg text-xs bg-[var(--secondary)] text-[var(--muted)] hover:bg-[var(--border)] transition-colors"
          >
            {t('Edit Profil', 'Edit Profile')}
          </button>
          <button
            onClick={handleReplan}
            disabled={replanLoading}
            className="px-3 py-1.5 rounded-lg text-xs bg-[var(--primary)] text-white hover:opacity-90 transition-colors disabled:opacity-50"
          >
            {replanLoading
              ? t('Menjana semula...', 'Re-planning...')
              : t('Rancang Semula', 'Re-plan')
            }
          </button>
        </div>
      </div>

      {/* Insights */}
      <PlannerInsights dashboardMode={dashboardMode} />

      {/* Weekly Plan */}
      {plan && planId && (
        <WeeklyPlanView
          plan={plan}
          planId={planId}
          dashboardMode={dashboardMode}
          completedTasks={completedTasks}
          onMarkComplete={handleMarkComplete}
        />
      )}

      {/* Score Modal */}
      {showScoreModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
          <div className="bento-card p-5 w-80 space-y-4">
            <h4 className="text-sm font-semibold text-[var(--foreground)]">
              {t('Nilaikan Pencapaian Kamu', 'Rate Your Performance')}
            </h4>
            <p className="text-xs text-[var(--muted)]">
              {showScoreModal.subject} — {showScoreModal.chapter}
            </p>
            <div className="space-y-2">
              <input
                type="range"
                min={0}
                max={100}
                value={scoreInput}
                onChange={(e) => setScoreInput(parseInt(e.target.value))}
                className="w-full accent-[var(--primary)]"
              />
              <p className="text-center text-lg font-bold text-[var(--foreground)]">{scoreInput}%</p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => setShowScoreModal(null)}
                className="flex-1 py-2 rounded-lg text-xs bg-[var(--secondary)] text-[var(--muted)]"
              >
                {t('Batal', 'Cancel')}
              </button>
              <button
                onClick={confirmComplete}
                className="flex-1 py-2 rounded-lg text-xs bg-[var(--primary)] text-white"
              >
                {t('Simpan', 'Save')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default StudyPlannerPage;
